###
# THIS FILE IS AUTOMATICALLY GENERATED
# Do not edit this file. It will be overwritten when the configure script is run.
###


######
# Build ID: 4b8575ee
######

4b8575ee_dirs_0 = .csconfig/4b8575ee/obj
4b8575ee_objs_0 = .csconfig/4b8575ee/obj/cache.o\
  .csconfig/4b8575ee/obj/cache_queues.o\
  .csconfig/4b8575ee/obj/champsim.o\
  .csconfig/4b8575ee/obj/dram_controller.o\
  .csconfig/4b8575ee/obj/json_printer.o\
  .csconfig/4b8575ee/obj/main.o\
  .csconfig/4b8575ee/obj/module_defs.o\
  .csconfig/4b8575ee/obj/ooo_cpu.o\
  .csconfig/4b8575ee/obj/plain_printer.o\
  .csconfig/4b8575ee/obj/ptw.o\
  .csconfig/4b8575ee/obj/tracereader.o\
  .csconfig/4b8575ee/obj/vmem.o
$(4b8575ee_objs_0): .csconfig/4b8575ee/obj/%.o: src/%.cc | $(4b8575ee_dirs_0)
-include $(wildcard .csconfig/4b8575ee/obj/*.d))

$(4b8575ee_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
bin/UCP: $(4b8575ee_objs_0)
build_dirs += $(4b8575ee_dirs_0)
build_objs += $(4b8575ee_objs_0)
bin/UCP: | bin
build_dirs += bin
executable_name += bin/UCP

###
# Build ID: 4b8575ee
# Module: btbDbasic_btb
# Source: btb/basic_btb
# Destination: .csconfig/4b8575ee/btbDbasic_btb
###

4b8575ee_btbDbasic_btb_dirs_0 = .csconfig/4b8575ee/btbDbasic_btb
4b8575ee_btbDbasic_btb_objs_0 = .csconfig/4b8575ee/btbDbasic_btb/basic_btb.o
$(4b8575ee_btbDbasic_btb_objs_0): .csconfig/4b8575ee/btbDbasic_btb/%.o: btb/basic_btb/%.cc | $(4b8575ee_btbDbasic_btb_dirs_0)
-include $(wildcard .csconfig/4b8575ee/btbDbasic_btb/*.d))

$(4b8575ee_btbDbasic_btb_objs_0): CPPFLAGS += -Ibtb/basic_btb
$(4b8575ee_btbDbasic_btb_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_btbDbasic_btb_objs_0): CPPFLAGS += -include btbDbasic_btb.inc
$(4b8575ee_btbDbasic_btb_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_btbDbasic_btb_objs_0)
module_dirs += $(4b8575ee_btbDbasic_btb_dirs_0)
module_objs += $(4b8575ee_btbDbasic_btb_objs_0)

###
# Build ID: 4b8575ee
# Module: btbDittage_64KB
# Source: btb/ittage_64KB
# Destination: .csconfig/4b8575ee/btbDittage_64KB
###

4b8575ee_btbDittage_64KB_dirs_0 = .csconfig/4b8575ee/btbDittage_64KB
4b8575ee_btbDittage_64KB_objs_0 = .csconfig/4b8575ee/btbDittage_64KB/basic_btb.o
$(4b8575ee_btbDittage_64KB_objs_0): .csconfig/4b8575ee/btbDittage_64KB/%.o: btb/ittage_64KB/%.cc | $(4b8575ee_btbDittage_64KB_dirs_0)
-include $(wildcard .csconfig/4b8575ee/btbDittage_64KB/*.d))

$(4b8575ee_btbDittage_64KB_objs_0): CPPFLAGS += -Ibtb/ittage_64KB
$(4b8575ee_btbDittage_64KB_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_btbDittage_64KB_objs_0): CPPFLAGS += -include btbDittage_64KB.inc
$(4b8575ee_btbDittage_64KB_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_btbDittage_64KB_objs_0)
module_dirs += $(4b8575ee_btbDittage_64KB_dirs_0)
module_objs += $(4b8575ee_btbDittage_64KB_objs_0)

###
# Build ID: 4b8575ee
# Module: btbDtwolevel_btb_1Ke_32Ke_gshare_ittage
# Source: btb/twolevel_btb_1Ke_32Ke_gshare_ittage
# Destination: .csconfig/4b8575ee/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage
###

4b8575ee_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_dirs_0 = .csconfig/4b8575ee/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage
4b8575ee_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0 = .csconfig/4b8575ee/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage/target_predictor.o
$(4b8575ee_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): .csconfig/4b8575ee/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage/%.o: btb/twolevel_btb_1Ke_32Ke_gshare_ittage/%.cc | $(4b8575ee_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_dirs_0)
-include $(wildcard .csconfig/4b8575ee/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage/*.d))

$(4b8575ee_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): CPPFLAGS += -Ibtb/twolevel_btb_1Ke_32Ke_gshare_ittage
$(4b8575ee_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): CPPFLAGS += -include btbDtwolevel_btb_1Ke_32Ke_gshare_ittage.inc
$(4b8575ee_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0)
module_dirs += $(4b8575ee_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_dirs_0)
module_objs += $(4b8575ee_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0)

###
# Build ID: 4b8575ee
# Module: branchDbatage
# Source: branch/batage
# Destination: .csconfig/4b8575ee/branchDbatage
###

4b8575ee_branchDbatage_dirs_0 = .csconfig/4b8575ee/branchDbatage
4b8575ee_branchDbatage_objs_0 = .csconfig/4b8575ee/branchDbatage/batage.o\
  .csconfig/4b8575ee/branchDbatage/btage_predictor.o
$(4b8575ee_branchDbatage_objs_0): .csconfig/4b8575ee/branchDbatage/%.o: branch/batage/%.cc | $(4b8575ee_branchDbatage_dirs_0)
-include $(wildcard .csconfig/4b8575ee/branchDbatage/*.d))

$(4b8575ee_branchDbatage_objs_0): CPPFLAGS += -Ibranch/batage
$(4b8575ee_branchDbatage_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_branchDbatage_objs_0): CPPFLAGS += -include branchDbatage.inc
$(4b8575ee_branchDbatage_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_branchDbatage_objs_0)
module_dirs += $(4b8575ee_branchDbatage_dirs_0)
module_objs += $(4b8575ee_branchDbatage_objs_0)

###
# Build ID: 4b8575ee
# Module: branchDbimodal
# Source: branch/bimodal
# Destination: .csconfig/4b8575ee/branchDbimodal
###

4b8575ee_branchDbimodal_dirs_0 = .csconfig/4b8575ee/branchDbimodal
4b8575ee_branchDbimodal_objs_0 = .csconfig/4b8575ee/branchDbimodal/bimodal.o
$(4b8575ee_branchDbimodal_objs_0): .csconfig/4b8575ee/branchDbimodal/%.o: branch/bimodal/%.cc | $(4b8575ee_branchDbimodal_dirs_0)
-include $(wildcard .csconfig/4b8575ee/branchDbimodal/*.d))

$(4b8575ee_branchDbimodal_objs_0): CPPFLAGS += -Ibranch/bimodal
$(4b8575ee_branchDbimodal_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_branchDbimodal_objs_0): CPPFLAGS += -include branchDbimodal.inc
$(4b8575ee_branchDbimodal_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_branchDbimodal_objs_0)
module_dirs += $(4b8575ee_branchDbimodal_dirs_0)
module_objs += $(4b8575ee_branchDbimodal_objs_0)

###
# Build ID: 4b8575ee
# Module: branchDgshare
# Source: branch/gshare
# Destination: .csconfig/4b8575ee/branchDgshare
###

4b8575ee_branchDgshare_dirs_0 = .csconfig/4b8575ee/branchDgshare
4b8575ee_branchDgshare_objs_0 = .csconfig/4b8575ee/branchDgshare/gshare.o
$(4b8575ee_branchDgshare_objs_0): .csconfig/4b8575ee/branchDgshare/%.o: branch/gshare/%.cc | $(4b8575ee_branchDgshare_dirs_0)
-include $(wildcard .csconfig/4b8575ee/branchDgshare/*.d))

$(4b8575ee_branchDgshare_objs_0): CPPFLAGS += -Ibranch/gshare
$(4b8575ee_branchDgshare_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_branchDgshare_objs_0): CPPFLAGS += -include branchDgshare.inc
$(4b8575ee_branchDgshare_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_branchDgshare_objs_0)
module_dirs += $(4b8575ee_branchDgshare_dirs_0)
module_objs += $(4b8575ee_branchDgshare_objs_0)

###
# Build ID: 4b8575ee
# Module: branchDhashed_perceptron
# Source: branch/hashed_perceptron
# Destination: .csconfig/4b8575ee/branchDhashed_perceptron
###

4b8575ee_branchDhashed_perceptron_dirs_0 = .csconfig/4b8575ee/branchDhashed_perceptron
4b8575ee_branchDhashed_perceptron_objs_0 = .csconfig/4b8575ee/branchDhashed_perceptron/hashed_perceptron.o
$(4b8575ee_branchDhashed_perceptron_objs_0): .csconfig/4b8575ee/branchDhashed_perceptron/%.o: branch/hashed_perceptron/%.cc | $(4b8575ee_branchDhashed_perceptron_dirs_0)
-include $(wildcard .csconfig/4b8575ee/branchDhashed_perceptron/*.d))

$(4b8575ee_branchDhashed_perceptron_objs_0): CPPFLAGS += -Ibranch/hashed_perceptron
$(4b8575ee_branchDhashed_perceptron_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_branchDhashed_perceptron_objs_0): CPPFLAGS += -include branchDhashed_perceptron.inc
$(4b8575ee_branchDhashed_perceptron_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_branchDhashed_perceptron_objs_0)
module_dirs += $(4b8575ee_branchDhashed_perceptron_dirs_0)
module_objs += $(4b8575ee_branchDhashed_perceptron_objs_0)

###
# Build ID: 4b8575ee
# Module: branchDperceptron
# Source: branch/perceptron
# Destination: .csconfig/4b8575ee/branchDperceptron
###

4b8575ee_branchDperceptron_dirs_0 = .csconfig/4b8575ee/branchDperceptron
4b8575ee_branchDperceptron_objs_0 = .csconfig/4b8575ee/branchDperceptron/perceptron.o
$(4b8575ee_branchDperceptron_objs_0): .csconfig/4b8575ee/branchDperceptron/%.o: branch/perceptron/%.cc | $(4b8575ee_branchDperceptron_dirs_0)
-include $(wildcard .csconfig/4b8575ee/branchDperceptron/*.d))

$(4b8575ee_branchDperceptron_objs_0): CPPFLAGS += -Ibranch/perceptron
$(4b8575ee_branchDperceptron_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_branchDperceptron_objs_0): CPPFLAGS += -include branchDperceptron.inc
$(4b8575ee_branchDperceptron_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_branchDperceptron_objs_0)
module_dirs += $(4b8575ee_branchDperceptron_dirs_0)
module_objs += $(4b8575ee_branchDperceptron_objs_0)

###
# Build ID: 4b8575ee
# Module: branchDtage_sc_l
# Source: branch/tage_sc_l
# Destination: .csconfig/4b8575ee/branchDtage_sc_l
###

4b8575ee_branchDtage_sc_l_dirs_0 = .csconfig/4b8575ee/branchDtage_sc_l
4b8575ee_branchDtage_sc_l_objs_0 = .csconfig/4b8575ee/branchDtage_sc_l/tage_sc_l.o
$(4b8575ee_branchDtage_sc_l_objs_0): .csconfig/4b8575ee/branchDtage_sc_l/%.o: branch/tage_sc_l/%.cc | $(4b8575ee_branchDtage_sc_l_dirs_0)
-include $(wildcard .csconfig/4b8575ee/branchDtage_sc_l/*.d))

$(4b8575ee_branchDtage_sc_l_objs_0): CPPFLAGS += -Ibranch/tage_sc_l
$(4b8575ee_branchDtage_sc_l_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_branchDtage_sc_l_objs_0): CPPFLAGS += -include branchDtage_sc_l.inc
$(4b8575ee_branchDtage_sc_l_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_branchDtage_sc_l_objs_0)
module_dirs += $(4b8575ee_branchDtage_sc_l_dirs_0)
module_objs += $(4b8575ee_branchDtage_sc_l_objs_0)

###
# Build ID: 4b8575ee
# Module: prefetcherDDHJOLT_instr
# Source: prefetcher/D-JOLT_instr
# Destination: .csconfig/4b8575ee/prefetcherDDHJOLT_instr
###

4b8575ee_prefetcherDDHJOLT_instr_dirs_0 = .csconfig/4b8575ee/prefetcherDDHJOLT_instr
4b8575ee_prefetcherDDHJOLT_instr_objs_0 = .csconfig/4b8575ee/prefetcherDDHJOLT_instr/d_jolt.o
$(4b8575ee_prefetcherDDHJOLT_instr_objs_0): .csconfig/4b8575ee/prefetcherDDHJOLT_instr/%.o: prefetcher/D-JOLT_instr/%.cc | $(4b8575ee_prefetcherDDHJOLT_instr_dirs_0)
-include $(wildcard .csconfig/4b8575ee/prefetcherDDHJOLT_instr/*.d))

$(4b8575ee_prefetcherDDHJOLT_instr_objs_0): CPPFLAGS += -Iprefetcher/D-JOLT_instr
$(4b8575ee_prefetcherDDHJOLT_instr_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_prefetcherDDHJOLT_instr_objs_0): CPPFLAGS += -include prefetcherDDHJOLT_instr.inc
$(4b8575ee_prefetcherDDHJOLT_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_prefetcherDDHJOLT_instr_objs_0)
module_dirs += $(4b8575ee_prefetcherDDHJOLT_instr_dirs_0)
module_objs += $(4b8575ee_prefetcherDDHJOLT_instr_objs_0)

###
# Build ID: 4b8575ee
# Module: prefetcherDFNLHMMA_instr
# Source: prefetcher/FNL-MMA_instr
# Destination: .csconfig/4b8575ee/prefetcherDFNLHMMA_instr
###

4b8575ee_prefetcherDFNLHMMA_instr_dirs_0 = .csconfig/4b8575ee/prefetcherDFNLHMMA_instr
4b8575ee_prefetcherDFNLHMMA_instr_objs_0 = .csconfig/4b8575ee/prefetcherDFNLHMMA_instr/fnl_mma.o
$(4b8575ee_prefetcherDFNLHMMA_instr_objs_0): .csconfig/4b8575ee/prefetcherDFNLHMMA_instr/%.o: prefetcher/FNL-MMA_instr/%.cc | $(4b8575ee_prefetcherDFNLHMMA_instr_dirs_0)
-include $(wildcard .csconfig/4b8575ee/prefetcherDFNLHMMA_instr/*.d))

$(4b8575ee_prefetcherDFNLHMMA_instr_objs_0): CPPFLAGS += -Iprefetcher/FNL-MMA_instr
$(4b8575ee_prefetcherDFNLHMMA_instr_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_prefetcherDFNLHMMA_instr_objs_0): CPPFLAGS += -include prefetcherDFNLHMMA_instr.inc
$(4b8575ee_prefetcherDFNLHMMA_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_prefetcherDFNLHMMA_instr_objs_0)
module_dirs += $(4b8575ee_prefetcherDFNLHMMA_instr_dirs_0)
module_objs += $(4b8575ee_prefetcherDFNLHMMA_instr_objs_0)

###
# Build ID: 4b8575ee
# Module: prefetcherDISCA_Entangling_4Ke_instr
# Source: prefetcher/ISCA_Entangling_4Ke_instr
# Destination: .csconfig/4b8575ee/prefetcherDISCA_Entangling_4Ke_instr
###

4b8575ee_prefetcherDISCA_Entangling_4Ke_instr_dirs_0 = .csconfig/4b8575ee/prefetcherDISCA_Entangling_4Ke_instr
4b8575ee_prefetcherDISCA_Entangling_4Ke_instr_objs_0 = .csconfig/4b8575ee/prefetcherDISCA_Entangling_4Ke_instr/ISCA_Entangling_4Ke.o
$(4b8575ee_prefetcherDISCA_Entangling_4Ke_instr_objs_0): .csconfig/4b8575ee/prefetcherDISCA_Entangling_4Ke_instr/%.o: prefetcher/ISCA_Entangling_4Ke_instr/%.cc | $(4b8575ee_prefetcherDISCA_Entangling_4Ke_instr_dirs_0)
-include $(wildcard .csconfig/4b8575ee/prefetcherDISCA_Entangling_4Ke_instr/*.d))

$(4b8575ee_prefetcherDISCA_Entangling_4Ke_instr_objs_0): CPPFLAGS += -Iprefetcher/ISCA_Entangling_4Ke_instr
$(4b8575ee_prefetcherDISCA_Entangling_4Ke_instr_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_prefetcherDISCA_Entangling_4Ke_instr_objs_0): CPPFLAGS += -include prefetcherDISCA_Entangling_4Ke_instr.inc
$(4b8575ee_prefetcherDISCA_Entangling_4Ke_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_prefetcherDISCA_Entangling_4Ke_instr_objs_0)
module_dirs += $(4b8575ee_prefetcherDISCA_Entangling_4Ke_instr_dirs_0)
module_objs += $(4b8575ee_prefetcherDISCA_Entangling_4Ke_instr_objs_0)

###
# Build ID: 4b8575ee
# Module: prefetcherDip_stride
# Source: prefetcher/ip_stride
# Destination: .csconfig/4b8575ee/prefetcherDip_stride
###

4b8575ee_prefetcherDip_stride_dirs_0 = .csconfig/4b8575ee/prefetcherDip_stride
4b8575ee_prefetcherDip_stride_objs_0 = .csconfig/4b8575ee/prefetcherDip_stride/ip_stride.o
$(4b8575ee_prefetcherDip_stride_objs_0): .csconfig/4b8575ee/prefetcherDip_stride/%.o: prefetcher/ip_stride/%.cc | $(4b8575ee_prefetcherDip_stride_dirs_0)
-include $(wildcard .csconfig/4b8575ee/prefetcherDip_stride/*.d))

$(4b8575ee_prefetcherDip_stride_objs_0): CPPFLAGS += -Iprefetcher/ip_stride
$(4b8575ee_prefetcherDip_stride_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_prefetcherDip_stride_objs_0): CPPFLAGS += -include prefetcherDip_stride.inc
$(4b8575ee_prefetcherDip_stride_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_prefetcherDip_stride_objs_0)
module_dirs += $(4b8575ee_prefetcherDip_stride_dirs_0)
module_objs += $(4b8575ee_prefetcherDip_stride_objs_0)

###
# Build ID: 4b8575ee
# Module: prefetcherDmini_djolt_instr
# Source: prefetcher/mini_djolt_instr
# Destination: .csconfig/4b8575ee/prefetcherDmini_djolt_instr
###

4b8575ee_prefetcherDmini_djolt_instr_dirs_0 = .csconfig/4b8575ee/prefetcherDmini_djolt_instr
4b8575ee_prefetcherDmini_djolt_instr_objs_0 = .csconfig/4b8575ee/prefetcherDmini_djolt_instr/mini_djolt.o
$(4b8575ee_prefetcherDmini_djolt_instr_objs_0): .csconfig/4b8575ee/prefetcherDmini_djolt_instr/%.o: prefetcher/mini_djolt_instr/%.cc | $(4b8575ee_prefetcherDmini_djolt_instr_dirs_0)
-include $(wildcard .csconfig/4b8575ee/prefetcherDmini_djolt_instr/*.d))

$(4b8575ee_prefetcherDmini_djolt_instr_objs_0): CPPFLAGS += -Iprefetcher/mini_djolt_instr
$(4b8575ee_prefetcherDmini_djolt_instr_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_prefetcherDmini_djolt_instr_objs_0): CPPFLAGS += -include prefetcherDmini_djolt_instr.inc
$(4b8575ee_prefetcherDmini_djolt_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_prefetcherDmini_djolt_instr_objs_0)
module_dirs += $(4b8575ee_prefetcherDmini_djolt_instr_dirs_0)
module_objs += $(4b8575ee_prefetcherDmini_djolt_instr_objs_0)

###
# Build ID: 4b8575ee
# Module: prefetcherDnext_line
# Source: prefetcher/next_line
# Destination: .csconfig/4b8575ee/prefetcherDnext_line
###

4b8575ee_prefetcherDnext_line_dirs_0 = .csconfig/4b8575ee/prefetcherDnext_line
4b8575ee_prefetcherDnext_line_objs_0 = .csconfig/4b8575ee/prefetcherDnext_line/next_line.o
$(4b8575ee_prefetcherDnext_line_objs_0): .csconfig/4b8575ee/prefetcherDnext_line/%.o: prefetcher/next_line/%.cc | $(4b8575ee_prefetcherDnext_line_dirs_0)
-include $(wildcard .csconfig/4b8575ee/prefetcherDnext_line/*.d))

$(4b8575ee_prefetcherDnext_line_objs_0): CPPFLAGS += -Iprefetcher/next_line
$(4b8575ee_prefetcherDnext_line_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_prefetcherDnext_line_objs_0): CPPFLAGS += -include prefetcherDnext_line.inc
$(4b8575ee_prefetcherDnext_line_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_prefetcherDnext_line_objs_0)
module_dirs += $(4b8575ee_prefetcherDnext_line_dirs_0)
module_objs += $(4b8575ee_prefetcherDnext_line_objs_0)

###
# Build ID: 4b8575ee
# Module: prefetcherDnext_line_instr
# Source: prefetcher/next_line_instr
# Destination: .csconfig/4b8575ee/prefetcherDnext_line_instr
###

4b8575ee_prefetcherDnext_line_instr_dirs_0 = .csconfig/4b8575ee/prefetcherDnext_line_instr
4b8575ee_prefetcherDnext_line_instr_objs_0 = .csconfig/4b8575ee/prefetcherDnext_line_instr/next_line.o
$(4b8575ee_prefetcherDnext_line_instr_objs_0): .csconfig/4b8575ee/prefetcherDnext_line_instr/%.o: prefetcher/next_line_instr/%.cc | $(4b8575ee_prefetcherDnext_line_instr_dirs_0)
-include $(wildcard .csconfig/4b8575ee/prefetcherDnext_line_instr/*.d))

$(4b8575ee_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -Iprefetcher/next_line_instr
$(4b8575ee_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -include prefetcherDnext_line_instr.inc
$(4b8575ee_prefetcherDnext_line_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_prefetcherDnext_line_instr_objs_0)
module_dirs += $(4b8575ee_prefetcherDnext_line_instr_dirs_0)
module_objs += $(4b8575ee_prefetcherDnext_line_instr_objs_0)

###
# Build ID: 4b8575ee
# Module: prefetcherDno
# Source: prefetcher/no
# Destination: .csconfig/4b8575ee/prefetcherDno
###

4b8575ee_prefetcherDno_dirs_0 = .csconfig/4b8575ee/prefetcherDno
4b8575ee_prefetcherDno_objs_0 = .csconfig/4b8575ee/prefetcherDno/no.o
$(4b8575ee_prefetcherDno_objs_0): .csconfig/4b8575ee/prefetcherDno/%.o: prefetcher/no/%.cc | $(4b8575ee_prefetcherDno_dirs_0)
-include $(wildcard .csconfig/4b8575ee/prefetcherDno/*.d))

$(4b8575ee_prefetcherDno_objs_0): CPPFLAGS += -Iprefetcher/no
$(4b8575ee_prefetcherDno_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_prefetcherDno_objs_0): CPPFLAGS += -include prefetcherDno.inc
$(4b8575ee_prefetcherDno_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_prefetcherDno_objs_0)
module_dirs += $(4b8575ee_prefetcherDno_dirs_0)
module_objs += $(4b8575ee_prefetcherDno_objs_0)

###
# Build ID: 4b8575ee
# Module: prefetcherDno_instr
# Source: prefetcher/no_instr
# Destination: .csconfig/4b8575ee/prefetcherDno_instr
###

4b8575ee_prefetcherDno_instr_dirs_0 = .csconfig/4b8575ee/prefetcherDno_instr
4b8575ee_prefetcherDno_instr_objs_0 = .csconfig/4b8575ee/prefetcherDno_instr/no.o
$(4b8575ee_prefetcherDno_instr_objs_0): .csconfig/4b8575ee/prefetcherDno_instr/%.o: prefetcher/no_instr/%.cc | $(4b8575ee_prefetcherDno_instr_dirs_0)
-include $(wildcard .csconfig/4b8575ee/prefetcherDno_instr/*.d))

$(4b8575ee_prefetcherDno_instr_objs_0): CPPFLAGS += -Iprefetcher/no_instr
$(4b8575ee_prefetcherDno_instr_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_prefetcherDno_instr_objs_0): CPPFLAGS += -include prefetcherDno_instr.inc
$(4b8575ee_prefetcherDno_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_prefetcherDno_instr_objs_0)
module_dirs += $(4b8575ee_prefetcherDno_instr_dirs_0)
module_objs += $(4b8575ee_prefetcherDno_instr_objs_0)

###
# Build ID: 4b8575ee
# Module: prefetcherDspp_dev
# Source: prefetcher/spp_dev
# Destination: .csconfig/4b8575ee/prefetcherDspp_dev
###

4b8575ee_prefetcherDspp_dev_dirs_0 = .csconfig/4b8575ee/prefetcherDspp_dev
4b8575ee_prefetcherDspp_dev_objs_0 = .csconfig/4b8575ee/prefetcherDspp_dev/spp_dev.o
$(4b8575ee_prefetcherDspp_dev_objs_0): .csconfig/4b8575ee/prefetcherDspp_dev/%.o: prefetcher/spp_dev/%.cc | $(4b8575ee_prefetcherDspp_dev_dirs_0)
-include $(wildcard .csconfig/4b8575ee/prefetcherDspp_dev/*.d))

$(4b8575ee_prefetcherDspp_dev_objs_0): CPPFLAGS += -Iprefetcher/spp_dev
$(4b8575ee_prefetcherDspp_dev_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_prefetcherDspp_dev_objs_0): CPPFLAGS += -include prefetcherDspp_dev.inc
$(4b8575ee_prefetcherDspp_dev_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_prefetcherDspp_dev_objs_0)
module_dirs += $(4b8575ee_prefetcherDspp_dev_dirs_0)
module_objs += $(4b8575ee_prefetcherDspp_dev_objs_0)

###
# Build ID: 4b8575ee
# Module: prefetcherDva_ampm_lite
# Source: prefetcher/va_ampm_lite
# Destination: .csconfig/4b8575ee/prefetcherDva_ampm_lite
###

4b8575ee_prefetcherDva_ampm_lite_dirs_0 = .csconfig/4b8575ee/prefetcherDva_ampm_lite
4b8575ee_prefetcherDva_ampm_lite_objs_0 = .csconfig/4b8575ee/prefetcherDva_ampm_lite/va_ampm_lite.o
$(4b8575ee_prefetcherDva_ampm_lite_objs_0): .csconfig/4b8575ee/prefetcherDva_ampm_lite/%.o: prefetcher/va_ampm_lite/%.cc | $(4b8575ee_prefetcherDva_ampm_lite_dirs_0)
-include $(wildcard .csconfig/4b8575ee/prefetcherDva_ampm_lite/*.d))

$(4b8575ee_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -Iprefetcher/va_ampm_lite
$(4b8575ee_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -include prefetcherDva_ampm_lite.inc
$(4b8575ee_prefetcherDva_ampm_lite_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_prefetcherDva_ampm_lite_objs_0)
module_dirs += $(4b8575ee_prefetcherDva_ampm_lite_dirs_0)
module_objs += $(4b8575ee_prefetcherDva_ampm_lite_objs_0)

###
# Build ID: 4b8575ee
# Module: replacementDdrrip
# Source: replacement/drrip
# Destination: .csconfig/4b8575ee/replacementDdrrip
###

4b8575ee_replacementDdrrip_dirs_0 = .csconfig/4b8575ee/replacementDdrrip
4b8575ee_replacementDdrrip_objs_0 = .csconfig/4b8575ee/replacementDdrrip/drrip.o
$(4b8575ee_replacementDdrrip_objs_0): .csconfig/4b8575ee/replacementDdrrip/%.o: replacement/drrip/%.cc | $(4b8575ee_replacementDdrrip_dirs_0)
-include $(wildcard .csconfig/4b8575ee/replacementDdrrip/*.d))

$(4b8575ee_replacementDdrrip_objs_0): CPPFLAGS += -Ireplacement/drrip
$(4b8575ee_replacementDdrrip_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_replacementDdrrip_objs_0): CPPFLAGS += -include replacementDdrrip.inc
$(4b8575ee_replacementDdrrip_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_replacementDdrrip_objs_0)
module_dirs += $(4b8575ee_replacementDdrrip_dirs_0)
module_objs += $(4b8575ee_replacementDdrrip_objs_0)

###
# Build ID: 4b8575ee
# Module: replacementDhotloop
# Source: replacement/hotloop
# Destination: .csconfig/4b8575ee/replacementDhotloop
###

4b8575ee_replacementDhotloop_dirs_0 = .csconfig/4b8575ee/replacementDhotloop
4b8575ee_replacementDhotloop_objs_0 = .csconfig/4b8575ee/replacementDhotloop/hotloop.o
$(4b8575ee_replacementDhotloop_objs_0): .csconfig/4b8575ee/replacementDhotloop/%.o: replacement/hotloop/%.cc | $(4b8575ee_replacementDhotloop_dirs_0)
-include $(wildcard .csconfig/4b8575ee/replacementDhotloop/*.d))

$(4b8575ee_replacementDhotloop_objs_0): CPPFLAGS += -Ireplacement/hotloop
$(4b8575ee_replacementDhotloop_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_replacementDhotloop_objs_0): CPPFLAGS += -include replacementDhotloop.inc
$(4b8575ee_replacementDhotloop_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_replacementDhotloop_objs_0)
module_dirs += $(4b8575ee_replacementDhotloop_dirs_0)
module_objs += $(4b8575ee_replacementDhotloop_objs_0)

###
# Build ID: 4b8575ee
# Module: replacementDhotloop_lru
# Source: replacement/hotloop_lru
# Destination: .csconfig/4b8575ee/replacementDhotloop_lru
###

4b8575ee_replacementDhotloop_lru_dirs_0 = .csconfig/4b8575ee/replacementDhotloop_lru
4b8575ee_replacementDhotloop_lru_objs_0 = .csconfig/4b8575ee/replacementDhotloop_lru/hotloop_lru.o
$(4b8575ee_replacementDhotloop_lru_objs_0): .csconfig/4b8575ee/replacementDhotloop_lru/%.o: replacement/hotloop_lru/%.cc | $(4b8575ee_replacementDhotloop_lru_dirs_0)
-include $(wildcard .csconfig/4b8575ee/replacementDhotloop_lru/*.d))

$(4b8575ee_replacementDhotloop_lru_objs_0): CPPFLAGS += -Ireplacement/hotloop_lru
$(4b8575ee_replacementDhotloop_lru_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_replacementDhotloop_lru_objs_0): CPPFLAGS += -include replacementDhotloop_lru.inc
$(4b8575ee_replacementDhotloop_lru_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_replacementDhotloop_lru_objs_0)
module_dirs += $(4b8575ee_replacementDhotloop_lru_dirs_0)
module_objs += $(4b8575ee_replacementDhotloop_lru_objs_0)

###
# Build ID: 4b8575ee
# Module: replacementDlru
# Source: replacement/lru
# Destination: .csconfig/4b8575ee/replacementDlru
###

4b8575ee_replacementDlru_dirs_0 = .csconfig/4b8575ee/replacementDlru
4b8575ee_replacementDlru_objs_0 = .csconfig/4b8575ee/replacementDlru/lru.o
$(4b8575ee_replacementDlru_objs_0): .csconfig/4b8575ee/replacementDlru/%.o: replacement/lru/%.cc | $(4b8575ee_replacementDlru_dirs_0)
-include $(wildcard .csconfig/4b8575ee/replacementDlru/*.d))

$(4b8575ee_replacementDlru_objs_0): CPPFLAGS += -Ireplacement/lru
$(4b8575ee_replacementDlru_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_replacementDlru_objs_0): CPPFLAGS += -include replacementDlru.inc
$(4b8575ee_replacementDlru_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_replacementDlru_objs_0)
module_dirs += $(4b8575ee_replacementDlru_dirs_0)
module_objs += $(4b8575ee_replacementDlru_objs_0)

###
# Build ID: 4b8575ee
# Module: replacementDship
# Source: replacement/ship
# Destination: .csconfig/4b8575ee/replacementDship
###

4b8575ee_replacementDship_dirs_0 = .csconfig/4b8575ee/replacementDship
4b8575ee_replacementDship_objs_0 = .csconfig/4b8575ee/replacementDship/ship.o
$(4b8575ee_replacementDship_objs_0): .csconfig/4b8575ee/replacementDship/%.o: replacement/ship/%.cc | $(4b8575ee_replacementDship_dirs_0)
-include $(wildcard .csconfig/4b8575ee/replacementDship/*.d))

$(4b8575ee_replacementDship_objs_0): CPPFLAGS += -Ireplacement/ship
$(4b8575ee_replacementDship_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_replacementDship_objs_0): CPPFLAGS += -include replacementDship.inc
$(4b8575ee_replacementDship_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_replacementDship_objs_0)
module_dirs += $(4b8575ee_replacementDship_dirs_0)
module_objs += $(4b8575ee_replacementDship_objs_0)

###
# Build ID: 4b8575ee
# Module: replacementDsrrip
# Source: replacement/srrip
# Destination: .csconfig/4b8575ee/replacementDsrrip
###

4b8575ee_replacementDsrrip_dirs_0 = .csconfig/4b8575ee/replacementDsrrip
4b8575ee_replacementDsrrip_objs_0 = .csconfig/4b8575ee/replacementDsrrip/srrip.o
$(4b8575ee_replacementDsrrip_objs_0): .csconfig/4b8575ee/replacementDsrrip/%.o: replacement/srrip/%.cc | $(4b8575ee_replacementDsrrip_dirs_0)
-include $(wildcard .csconfig/4b8575ee/replacementDsrrip/*.d))

$(4b8575ee_replacementDsrrip_objs_0): CPPFLAGS += -Ireplacement/srrip
$(4b8575ee_replacementDsrrip_objs_0): CPPFLAGS += -I.csconfig/4b8575ee/inc
$(4b8575ee_replacementDsrrip_objs_0): CPPFLAGS += -include replacementDsrrip.inc
$(4b8575ee_replacementDsrrip_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/UCP: $(4b8575ee_replacementDsrrip_objs_0)
module_dirs += $(4b8575ee_replacementDsrrip_dirs_0)
module_objs += $(4b8575ee_replacementDsrrip_objs_0)

######
# Build ID: d6ee6fa2
######

d6ee6fa2_dirs_0 = .csconfig/test/d6ee6fa2/obj
d6ee6fa2_objs_0 = .csconfig/test/d6ee6fa2/obj/cache.o\
  .csconfig/test/d6ee6fa2/obj/cache_queues.o\
  .csconfig/test/d6ee6fa2/obj/champsim.o\
  .csconfig/test/d6ee6fa2/obj/dram_controller.o\
  .csconfig/test/d6ee6fa2/obj/json_printer.o\
  .csconfig/test/d6ee6fa2/obj/main.o\
  .csconfig/test/d6ee6fa2/obj/module_defs.o\
  .csconfig/test/d6ee6fa2/obj/ooo_cpu.o\
  .csconfig/test/d6ee6fa2/obj/plain_printer.o\
  .csconfig/test/d6ee6fa2/obj/ptw.o\
  .csconfig/test/d6ee6fa2/obj/tracereader.o\
  .csconfig/test/d6ee6fa2/obj/vmem.o
$(d6ee6fa2_objs_0): .csconfig/test/d6ee6fa2/obj/%.o: src/%.cc | $(d6ee6fa2_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/obj/*.d))

$(d6ee6fa2_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
test/bin/000-test-main: $(d6ee6fa2_objs_0)
build_dirs += $(d6ee6fa2_dirs_0)
build_objs += $(d6ee6fa2_objs_0)
test/bin/000-test-main: | test/bin
build_dirs += test/bin
executable_name += test/bin/000-test-main

###
# Build ID: d6ee6fa2
# Module: btbDbasic_btb
# Source: btb/basic_btb
# Destination: .csconfig/test/d6ee6fa2/btbDbasic_btb
###

d6ee6fa2_btbDbasic_btb_dirs_0 = .csconfig/test/d6ee6fa2/btbDbasic_btb
d6ee6fa2_btbDbasic_btb_objs_0 = .csconfig/test/d6ee6fa2/btbDbasic_btb/basic_btb.o
$(d6ee6fa2_btbDbasic_btb_objs_0): .csconfig/test/d6ee6fa2/btbDbasic_btb/%.o: btb/basic_btb/%.cc | $(d6ee6fa2_btbDbasic_btb_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/btbDbasic_btb/*.d))

$(d6ee6fa2_btbDbasic_btb_objs_0): CPPFLAGS += -Ibtb/basic_btb
$(d6ee6fa2_btbDbasic_btb_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_btbDbasic_btb_objs_0): CPPFLAGS += -include btbDbasic_btb.inc
$(d6ee6fa2_btbDbasic_btb_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_btbDbasic_btb_objs_0)
module_dirs += $(d6ee6fa2_btbDbasic_btb_dirs_0)
module_objs += $(d6ee6fa2_btbDbasic_btb_objs_0)

###
# Build ID: d6ee6fa2
# Module: btbDittage_64KB
# Source: btb/ittage_64KB
# Destination: .csconfig/test/d6ee6fa2/btbDittage_64KB
###

d6ee6fa2_btbDittage_64KB_dirs_0 = .csconfig/test/d6ee6fa2/btbDittage_64KB
d6ee6fa2_btbDittage_64KB_objs_0 = .csconfig/test/d6ee6fa2/btbDittage_64KB/basic_btb.o
$(d6ee6fa2_btbDittage_64KB_objs_0): .csconfig/test/d6ee6fa2/btbDittage_64KB/%.o: btb/ittage_64KB/%.cc | $(d6ee6fa2_btbDittage_64KB_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/btbDittage_64KB/*.d))

$(d6ee6fa2_btbDittage_64KB_objs_0): CPPFLAGS += -Ibtb/ittage_64KB
$(d6ee6fa2_btbDittage_64KB_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_btbDittage_64KB_objs_0): CPPFLAGS += -include btbDittage_64KB.inc
$(d6ee6fa2_btbDittage_64KB_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_btbDittage_64KB_objs_0)
module_dirs += $(d6ee6fa2_btbDittage_64KB_dirs_0)
module_objs += $(d6ee6fa2_btbDittage_64KB_objs_0)

###
# Build ID: d6ee6fa2
# Module: btbDtwolevel_btb_1Ke_32Ke_gshare_ittage
# Source: btb/twolevel_btb_1Ke_32Ke_gshare_ittage
# Destination: .csconfig/test/d6ee6fa2/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage
###

d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_dirs_0 = .csconfig/test/d6ee6fa2/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage
d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0 = .csconfig/test/d6ee6fa2/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage/target_predictor.o
$(d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): .csconfig/test/d6ee6fa2/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage/%.o: btb/twolevel_btb_1Ke_32Ke_gshare_ittage/%.cc | $(d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage/*.d))

$(d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): CPPFLAGS += -Ibtb/twolevel_btb_1Ke_32Ke_gshare_ittage
$(d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): CPPFLAGS += -include btbDtwolevel_btb_1Ke_32Ke_gshare_ittage.inc
$(d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0)
module_dirs += $(d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_dirs_0)
module_objs += $(d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0)

###
# Build ID: d6ee6fa2
# Module: branchDbatage
# Source: branch/batage
# Destination: .csconfig/test/d6ee6fa2/branchDbatage
###

d6ee6fa2_branchDbatage_dirs_0 = .csconfig/test/d6ee6fa2/branchDbatage
d6ee6fa2_branchDbatage_objs_0 = .csconfig/test/d6ee6fa2/branchDbatage/batage.o\
  .csconfig/test/d6ee6fa2/branchDbatage/btage_predictor.o
$(d6ee6fa2_branchDbatage_objs_0): .csconfig/test/d6ee6fa2/branchDbatage/%.o: branch/batage/%.cc | $(d6ee6fa2_branchDbatage_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/branchDbatage/*.d))

$(d6ee6fa2_branchDbatage_objs_0): CPPFLAGS += -Ibranch/batage
$(d6ee6fa2_branchDbatage_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_branchDbatage_objs_0): CPPFLAGS += -include branchDbatage.inc
$(d6ee6fa2_branchDbatage_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_branchDbatage_objs_0)
module_dirs += $(d6ee6fa2_branchDbatage_dirs_0)
module_objs += $(d6ee6fa2_branchDbatage_objs_0)

###
# Build ID: d6ee6fa2
# Module: branchDbimodal
# Source: branch/bimodal
# Destination: .csconfig/test/d6ee6fa2/branchDbimodal
###

d6ee6fa2_branchDbimodal_dirs_0 = .csconfig/test/d6ee6fa2/branchDbimodal
d6ee6fa2_branchDbimodal_objs_0 = .csconfig/test/d6ee6fa2/branchDbimodal/bimodal.o
$(d6ee6fa2_branchDbimodal_objs_0): .csconfig/test/d6ee6fa2/branchDbimodal/%.o: branch/bimodal/%.cc | $(d6ee6fa2_branchDbimodal_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/branchDbimodal/*.d))

$(d6ee6fa2_branchDbimodal_objs_0): CPPFLAGS += -Ibranch/bimodal
$(d6ee6fa2_branchDbimodal_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_branchDbimodal_objs_0): CPPFLAGS += -include branchDbimodal.inc
$(d6ee6fa2_branchDbimodal_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_branchDbimodal_objs_0)
module_dirs += $(d6ee6fa2_branchDbimodal_dirs_0)
module_objs += $(d6ee6fa2_branchDbimodal_objs_0)

###
# Build ID: d6ee6fa2
# Module: branchDgshare
# Source: branch/gshare
# Destination: .csconfig/test/d6ee6fa2/branchDgshare
###

d6ee6fa2_branchDgshare_dirs_0 = .csconfig/test/d6ee6fa2/branchDgshare
d6ee6fa2_branchDgshare_objs_0 = .csconfig/test/d6ee6fa2/branchDgshare/gshare.o
$(d6ee6fa2_branchDgshare_objs_0): .csconfig/test/d6ee6fa2/branchDgshare/%.o: branch/gshare/%.cc | $(d6ee6fa2_branchDgshare_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/branchDgshare/*.d))

$(d6ee6fa2_branchDgshare_objs_0): CPPFLAGS += -Ibranch/gshare
$(d6ee6fa2_branchDgshare_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_branchDgshare_objs_0): CPPFLAGS += -include branchDgshare.inc
$(d6ee6fa2_branchDgshare_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_branchDgshare_objs_0)
module_dirs += $(d6ee6fa2_branchDgshare_dirs_0)
module_objs += $(d6ee6fa2_branchDgshare_objs_0)

###
# Build ID: d6ee6fa2
# Module: branchDhashed_perceptron
# Source: branch/hashed_perceptron
# Destination: .csconfig/test/d6ee6fa2/branchDhashed_perceptron
###

d6ee6fa2_branchDhashed_perceptron_dirs_0 = .csconfig/test/d6ee6fa2/branchDhashed_perceptron
d6ee6fa2_branchDhashed_perceptron_objs_0 = .csconfig/test/d6ee6fa2/branchDhashed_perceptron/hashed_perceptron.o
$(d6ee6fa2_branchDhashed_perceptron_objs_0): .csconfig/test/d6ee6fa2/branchDhashed_perceptron/%.o: branch/hashed_perceptron/%.cc | $(d6ee6fa2_branchDhashed_perceptron_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/branchDhashed_perceptron/*.d))

$(d6ee6fa2_branchDhashed_perceptron_objs_0): CPPFLAGS += -Ibranch/hashed_perceptron
$(d6ee6fa2_branchDhashed_perceptron_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_branchDhashed_perceptron_objs_0): CPPFLAGS += -include branchDhashed_perceptron.inc
$(d6ee6fa2_branchDhashed_perceptron_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_branchDhashed_perceptron_objs_0)
module_dirs += $(d6ee6fa2_branchDhashed_perceptron_dirs_0)
module_objs += $(d6ee6fa2_branchDhashed_perceptron_objs_0)

###
# Build ID: d6ee6fa2
# Module: branchDperceptron
# Source: branch/perceptron
# Destination: .csconfig/test/d6ee6fa2/branchDperceptron
###

d6ee6fa2_branchDperceptron_dirs_0 = .csconfig/test/d6ee6fa2/branchDperceptron
d6ee6fa2_branchDperceptron_objs_0 = .csconfig/test/d6ee6fa2/branchDperceptron/perceptron.o
$(d6ee6fa2_branchDperceptron_objs_0): .csconfig/test/d6ee6fa2/branchDperceptron/%.o: branch/perceptron/%.cc | $(d6ee6fa2_branchDperceptron_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/branchDperceptron/*.d))

$(d6ee6fa2_branchDperceptron_objs_0): CPPFLAGS += -Ibranch/perceptron
$(d6ee6fa2_branchDperceptron_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_branchDperceptron_objs_0): CPPFLAGS += -include branchDperceptron.inc
$(d6ee6fa2_branchDperceptron_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_branchDperceptron_objs_0)
module_dirs += $(d6ee6fa2_branchDperceptron_dirs_0)
module_objs += $(d6ee6fa2_branchDperceptron_objs_0)

###
# Build ID: d6ee6fa2
# Module: branchDtage_sc_l
# Source: branch/tage_sc_l
# Destination: .csconfig/test/d6ee6fa2/branchDtage_sc_l
###

d6ee6fa2_branchDtage_sc_l_dirs_0 = .csconfig/test/d6ee6fa2/branchDtage_sc_l
d6ee6fa2_branchDtage_sc_l_objs_0 = .csconfig/test/d6ee6fa2/branchDtage_sc_l/tage_sc_l.o
$(d6ee6fa2_branchDtage_sc_l_objs_0): .csconfig/test/d6ee6fa2/branchDtage_sc_l/%.o: branch/tage_sc_l/%.cc | $(d6ee6fa2_branchDtage_sc_l_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/branchDtage_sc_l/*.d))

$(d6ee6fa2_branchDtage_sc_l_objs_0): CPPFLAGS += -Ibranch/tage_sc_l
$(d6ee6fa2_branchDtage_sc_l_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_branchDtage_sc_l_objs_0): CPPFLAGS += -include branchDtage_sc_l.inc
$(d6ee6fa2_branchDtage_sc_l_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_branchDtage_sc_l_objs_0)
module_dirs += $(d6ee6fa2_branchDtage_sc_l_dirs_0)
module_objs += $(d6ee6fa2_branchDtage_sc_l_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDDHJOLT_instr
# Source: prefetcher/D-JOLT_instr
# Destination: .csconfig/test/d6ee6fa2/prefetcherDDHJOLT_instr
###

d6ee6fa2_prefetcherDDHJOLT_instr_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDDHJOLT_instr
d6ee6fa2_prefetcherDDHJOLT_instr_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDDHJOLT_instr/d_jolt.o
$(d6ee6fa2_prefetcherDDHJOLT_instr_objs_0): .csconfig/test/d6ee6fa2/prefetcherDDHJOLT_instr/%.o: prefetcher/D-JOLT_instr/%.cc | $(d6ee6fa2_prefetcherDDHJOLT_instr_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDDHJOLT_instr/*.d))

$(d6ee6fa2_prefetcherDDHJOLT_instr_objs_0): CPPFLAGS += -Iprefetcher/D-JOLT_instr
$(d6ee6fa2_prefetcherDDHJOLT_instr_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDDHJOLT_instr_objs_0): CPPFLAGS += -include prefetcherDDHJOLT_instr.inc
$(d6ee6fa2_prefetcherDDHJOLT_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDDHJOLT_instr_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDDHJOLT_instr_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDDHJOLT_instr_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDFNLHMMA_instr
# Source: prefetcher/FNL-MMA_instr
# Destination: .csconfig/test/d6ee6fa2/prefetcherDFNLHMMA_instr
###

d6ee6fa2_prefetcherDFNLHMMA_instr_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDFNLHMMA_instr
d6ee6fa2_prefetcherDFNLHMMA_instr_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDFNLHMMA_instr/fnl_mma.o
$(d6ee6fa2_prefetcherDFNLHMMA_instr_objs_0): .csconfig/test/d6ee6fa2/prefetcherDFNLHMMA_instr/%.o: prefetcher/FNL-MMA_instr/%.cc | $(d6ee6fa2_prefetcherDFNLHMMA_instr_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDFNLHMMA_instr/*.d))

$(d6ee6fa2_prefetcherDFNLHMMA_instr_objs_0): CPPFLAGS += -Iprefetcher/FNL-MMA_instr
$(d6ee6fa2_prefetcherDFNLHMMA_instr_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDFNLHMMA_instr_objs_0): CPPFLAGS += -include prefetcherDFNLHMMA_instr.inc
$(d6ee6fa2_prefetcherDFNLHMMA_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDFNLHMMA_instr_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDFNLHMMA_instr_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDFNLHMMA_instr_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDISCA_Entangling_4Ke_instr
# Source: prefetcher/ISCA_Entangling_4Ke_instr
# Destination: .csconfig/test/d6ee6fa2/prefetcherDISCA_Entangling_4Ke_instr
###

d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDISCA_Entangling_4Ke_instr
d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDISCA_Entangling_4Ke_instr/ISCA_Entangling_4Ke.o
$(d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_objs_0): .csconfig/test/d6ee6fa2/prefetcherDISCA_Entangling_4Ke_instr/%.o: prefetcher/ISCA_Entangling_4Ke_instr/%.cc | $(d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDISCA_Entangling_4Ke_instr/*.d))

$(d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_objs_0): CPPFLAGS += -Iprefetcher/ISCA_Entangling_4Ke_instr
$(d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_objs_0): CPPFLAGS += -include prefetcherDISCA_Entangling_4Ke_instr.inc
$(d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDip_stride
# Source: prefetcher/ip_stride
# Destination: .csconfig/test/d6ee6fa2/prefetcherDip_stride
###

d6ee6fa2_prefetcherDip_stride_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDip_stride
d6ee6fa2_prefetcherDip_stride_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDip_stride/ip_stride.o
$(d6ee6fa2_prefetcherDip_stride_objs_0): .csconfig/test/d6ee6fa2/prefetcherDip_stride/%.o: prefetcher/ip_stride/%.cc | $(d6ee6fa2_prefetcherDip_stride_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDip_stride/*.d))

$(d6ee6fa2_prefetcherDip_stride_objs_0): CPPFLAGS += -Iprefetcher/ip_stride
$(d6ee6fa2_prefetcherDip_stride_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDip_stride_objs_0): CPPFLAGS += -include prefetcherDip_stride.inc
$(d6ee6fa2_prefetcherDip_stride_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDip_stride_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDip_stride_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDip_stride_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDmini_djolt_instr
# Source: prefetcher/mini_djolt_instr
# Destination: .csconfig/test/d6ee6fa2/prefetcherDmini_djolt_instr
###

d6ee6fa2_prefetcherDmini_djolt_instr_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDmini_djolt_instr
d6ee6fa2_prefetcherDmini_djolt_instr_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDmini_djolt_instr/mini_djolt.o
$(d6ee6fa2_prefetcherDmini_djolt_instr_objs_0): .csconfig/test/d6ee6fa2/prefetcherDmini_djolt_instr/%.o: prefetcher/mini_djolt_instr/%.cc | $(d6ee6fa2_prefetcherDmini_djolt_instr_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDmini_djolt_instr/*.d))

$(d6ee6fa2_prefetcherDmini_djolt_instr_objs_0): CPPFLAGS += -Iprefetcher/mini_djolt_instr
$(d6ee6fa2_prefetcherDmini_djolt_instr_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDmini_djolt_instr_objs_0): CPPFLAGS += -include prefetcherDmini_djolt_instr.inc
$(d6ee6fa2_prefetcherDmini_djolt_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDmini_djolt_instr_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDmini_djolt_instr_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDmini_djolt_instr_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDnext_line
# Source: prefetcher/next_line
# Destination: .csconfig/test/d6ee6fa2/prefetcherDnext_line
###

d6ee6fa2_prefetcherDnext_line_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDnext_line
d6ee6fa2_prefetcherDnext_line_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDnext_line/next_line.o
$(d6ee6fa2_prefetcherDnext_line_objs_0): .csconfig/test/d6ee6fa2/prefetcherDnext_line/%.o: prefetcher/next_line/%.cc | $(d6ee6fa2_prefetcherDnext_line_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDnext_line/*.d))

$(d6ee6fa2_prefetcherDnext_line_objs_0): CPPFLAGS += -Iprefetcher/next_line
$(d6ee6fa2_prefetcherDnext_line_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDnext_line_objs_0): CPPFLAGS += -include prefetcherDnext_line.inc
$(d6ee6fa2_prefetcherDnext_line_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDnext_line_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDnext_line_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDnext_line_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDnext_line_instr
# Source: prefetcher/next_line_instr
# Destination: .csconfig/test/d6ee6fa2/prefetcherDnext_line_instr
###

d6ee6fa2_prefetcherDnext_line_instr_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDnext_line_instr
d6ee6fa2_prefetcherDnext_line_instr_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDnext_line_instr/next_line.o
$(d6ee6fa2_prefetcherDnext_line_instr_objs_0): .csconfig/test/d6ee6fa2/prefetcherDnext_line_instr/%.o: prefetcher/next_line_instr/%.cc | $(d6ee6fa2_prefetcherDnext_line_instr_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDnext_line_instr/*.d))

$(d6ee6fa2_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -Iprefetcher/next_line_instr
$(d6ee6fa2_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -include prefetcherDnext_line_instr.inc
$(d6ee6fa2_prefetcherDnext_line_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDnext_line_instr_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDnext_line_instr_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDnext_line_instr_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDno
# Source: prefetcher/no
# Destination: .csconfig/test/d6ee6fa2/prefetcherDno
###

d6ee6fa2_prefetcherDno_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDno
d6ee6fa2_prefetcherDno_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDno/no.o
$(d6ee6fa2_prefetcherDno_objs_0): .csconfig/test/d6ee6fa2/prefetcherDno/%.o: prefetcher/no/%.cc | $(d6ee6fa2_prefetcherDno_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDno/*.d))

$(d6ee6fa2_prefetcherDno_objs_0): CPPFLAGS += -Iprefetcher/no
$(d6ee6fa2_prefetcherDno_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDno_objs_0): CPPFLAGS += -include prefetcherDno.inc
$(d6ee6fa2_prefetcherDno_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDno_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDno_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDno_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDno_instr
# Source: prefetcher/no_instr
# Destination: .csconfig/test/d6ee6fa2/prefetcherDno_instr
###

d6ee6fa2_prefetcherDno_instr_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDno_instr
d6ee6fa2_prefetcherDno_instr_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDno_instr/no.o
$(d6ee6fa2_prefetcherDno_instr_objs_0): .csconfig/test/d6ee6fa2/prefetcherDno_instr/%.o: prefetcher/no_instr/%.cc | $(d6ee6fa2_prefetcherDno_instr_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDno_instr/*.d))

$(d6ee6fa2_prefetcherDno_instr_objs_0): CPPFLAGS += -Iprefetcher/no_instr
$(d6ee6fa2_prefetcherDno_instr_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDno_instr_objs_0): CPPFLAGS += -include prefetcherDno_instr.inc
$(d6ee6fa2_prefetcherDno_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDno_instr_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDno_instr_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDno_instr_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDspp_dev
# Source: prefetcher/spp_dev
# Destination: .csconfig/test/d6ee6fa2/prefetcherDspp_dev
###

d6ee6fa2_prefetcherDspp_dev_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDspp_dev
d6ee6fa2_prefetcherDspp_dev_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDspp_dev/spp_dev.o
$(d6ee6fa2_prefetcherDspp_dev_objs_0): .csconfig/test/d6ee6fa2/prefetcherDspp_dev/%.o: prefetcher/spp_dev/%.cc | $(d6ee6fa2_prefetcherDspp_dev_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDspp_dev/*.d))

$(d6ee6fa2_prefetcherDspp_dev_objs_0): CPPFLAGS += -Iprefetcher/spp_dev
$(d6ee6fa2_prefetcherDspp_dev_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDspp_dev_objs_0): CPPFLAGS += -include prefetcherDspp_dev.inc
$(d6ee6fa2_prefetcherDspp_dev_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDspp_dev_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDspp_dev_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDspp_dev_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDva_ampm_lite
# Source: prefetcher/va_ampm_lite
# Destination: .csconfig/test/d6ee6fa2/prefetcherDva_ampm_lite
###

d6ee6fa2_prefetcherDva_ampm_lite_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDva_ampm_lite
d6ee6fa2_prefetcherDva_ampm_lite_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDva_ampm_lite/va_ampm_lite.o
$(d6ee6fa2_prefetcherDva_ampm_lite_objs_0): .csconfig/test/d6ee6fa2/prefetcherDva_ampm_lite/%.o: prefetcher/va_ampm_lite/%.cc | $(d6ee6fa2_prefetcherDva_ampm_lite_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDva_ampm_lite/*.d))

$(d6ee6fa2_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -Iprefetcher/va_ampm_lite
$(d6ee6fa2_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -include prefetcherDva_ampm_lite.inc
$(d6ee6fa2_prefetcherDva_ampm_lite_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDva_ampm_lite_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDva_ampm_lite_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDva_ampm_lite_objs_0)

###
# Build ID: d6ee6fa2
# Module: replacementDdrrip
# Source: replacement/drrip
# Destination: .csconfig/test/d6ee6fa2/replacementDdrrip
###

d6ee6fa2_replacementDdrrip_dirs_0 = .csconfig/test/d6ee6fa2/replacementDdrrip
d6ee6fa2_replacementDdrrip_objs_0 = .csconfig/test/d6ee6fa2/replacementDdrrip/drrip.o
$(d6ee6fa2_replacementDdrrip_objs_0): .csconfig/test/d6ee6fa2/replacementDdrrip/%.o: replacement/drrip/%.cc | $(d6ee6fa2_replacementDdrrip_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/replacementDdrrip/*.d))

$(d6ee6fa2_replacementDdrrip_objs_0): CPPFLAGS += -Ireplacement/drrip
$(d6ee6fa2_replacementDdrrip_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_replacementDdrrip_objs_0): CPPFLAGS += -include replacementDdrrip.inc
$(d6ee6fa2_replacementDdrrip_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_replacementDdrrip_objs_0)
module_dirs += $(d6ee6fa2_replacementDdrrip_dirs_0)
module_objs += $(d6ee6fa2_replacementDdrrip_objs_0)

###
# Build ID: d6ee6fa2
# Module: replacementDhotloop
# Source: replacement/hotloop
# Destination: .csconfig/test/d6ee6fa2/replacementDhotloop
###

d6ee6fa2_replacementDhotloop_dirs_0 = .csconfig/test/d6ee6fa2/replacementDhotloop
d6ee6fa2_replacementDhotloop_objs_0 = .csconfig/test/d6ee6fa2/replacementDhotloop/hotloop.o
$(d6ee6fa2_replacementDhotloop_objs_0): .csconfig/test/d6ee6fa2/replacementDhotloop/%.o: replacement/hotloop/%.cc | $(d6ee6fa2_replacementDhotloop_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/replacementDhotloop/*.d))

$(d6ee6fa2_replacementDhotloop_objs_0): CPPFLAGS += -Ireplacement/hotloop
$(d6ee6fa2_replacementDhotloop_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_replacementDhotloop_objs_0): CPPFLAGS += -include replacementDhotloop.inc
$(d6ee6fa2_replacementDhotloop_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_replacementDhotloop_objs_0)
module_dirs += $(d6ee6fa2_replacementDhotloop_dirs_0)
module_objs += $(d6ee6fa2_replacementDhotloop_objs_0)

###
# Build ID: d6ee6fa2
# Module: replacementDhotloop_lru
# Source: replacement/hotloop_lru
# Destination: .csconfig/test/d6ee6fa2/replacementDhotloop_lru
###

d6ee6fa2_replacementDhotloop_lru_dirs_0 = .csconfig/test/d6ee6fa2/replacementDhotloop_lru
d6ee6fa2_replacementDhotloop_lru_objs_0 = .csconfig/test/d6ee6fa2/replacementDhotloop_lru/hotloop_lru.o
$(d6ee6fa2_replacementDhotloop_lru_objs_0): .csconfig/test/d6ee6fa2/replacementDhotloop_lru/%.o: replacement/hotloop_lru/%.cc | $(d6ee6fa2_replacementDhotloop_lru_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/replacementDhotloop_lru/*.d))

$(d6ee6fa2_replacementDhotloop_lru_objs_0): CPPFLAGS += -Ireplacement/hotloop_lru
$(d6ee6fa2_replacementDhotloop_lru_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_replacementDhotloop_lru_objs_0): CPPFLAGS += -include replacementDhotloop_lru.inc
$(d6ee6fa2_replacementDhotloop_lru_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_replacementDhotloop_lru_objs_0)
module_dirs += $(d6ee6fa2_replacementDhotloop_lru_dirs_0)
module_objs += $(d6ee6fa2_replacementDhotloop_lru_objs_0)

###
# Build ID: d6ee6fa2
# Module: replacementDlru
# Source: replacement/lru
# Destination: .csconfig/test/d6ee6fa2/replacementDlru
###

d6ee6fa2_replacementDlru_dirs_0 = .csconfig/test/d6ee6fa2/replacementDlru
d6ee6fa2_replacementDlru_objs_0 = .csconfig/test/d6ee6fa2/replacementDlru/lru.o
$(d6ee6fa2_replacementDlru_objs_0): .csconfig/test/d6ee6fa2/replacementDlru/%.o: replacement/lru/%.cc | $(d6ee6fa2_replacementDlru_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/replacementDlru/*.d))

$(d6ee6fa2_replacementDlru_objs_0): CPPFLAGS += -Ireplacement/lru
$(d6ee6fa2_replacementDlru_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_replacementDlru_objs_0): CPPFLAGS += -include replacementDlru.inc
$(d6ee6fa2_replacementDlru_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_replacementDlru_objs_0)
module_dirs += $(d6ee6fa2_replacementDlru_dirs_0)
module_objs += $(d6ee6fa2_replacementDlru_objs_0)

###
# Build ID: d6ee6fa2
# Module: replacementDship
# Source: replacement/ship
# Destination: .csconfig/test/d6ee6fa2/replacementDship
###

d6ee6fa2_replacementDship_dirs_0 = .csconfig/test/d6ee6fa2/replacementDship
d6ee6fa2_replacementDship_objs_0 = .csconfig/test/d6ee6fa2/replacementDship/ship.o
$(d6ee6fa2_replacementDship_objs_0): .csconfig/test/d6ee6fa2/replacementDship/%.o: replacement/ship/%.cc | $(d6ee6fa2_replacementDship_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/replacementDship/*.d))

$(d6ee6fa2_replacementDship_objs_0): CPPFLAGS += -Ireplacement/ship
$(d6ee6fa2_replacementDship_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_replacementDship_objs_0): CPPFLAGS += -include replacementDship.inc
$(d6ee6fa2_replacementDship_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_replacementDship_objs_0)
module_dirs += $(d6ee6fa2_replacementDship_dirs_0)
module_objs += $(d6ee6fa2_replacementDship_objs_0)

###
# Build ID: d6ee6fa2
# Module: replacementDsrrip
# Source: replacement/srrip
# Destination: .csconfig/test/d6ee6fa2/replacementDsrrip
###

d6ee6fa2_replacementDsrrip_dirs_0 = .csconfig/test/d6ee6fa2/replacementDsrrip
d6ee6fa2_replacementDsrrip_objs_0 = .csconfig/test/d6ee6fa2/replacementDsrrip/srrip.o
$(d6ee6fa2_replacementDsrrip_objs_0): .csconfig/test/d6ee6fa2/replacementDsrrip/%.o: replacement/srrip/%.cc | $(d6ee6fa2_replacementDsrrip_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/replacementDsrrip/*.d))

$(d6ee6fa2_replacementDsrrip_objs_0): CPPFLAGS += -Ireplacement/srrip
$(d6ee6fa2_replacementDsrrip_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_replacementDsrrip_objs_0): CPPFLAGS += -include replacementDsrrip.inc
$(d6ee6fa2_replacementDsrrip_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_replacementDsrrip_objs_0)
module_dirs += $(d6ee6fa2_replacementDsrrip_dirs_0)
module_objs += $(d6ee6fa2_replacementDsrrip_objs_0)