###
# THIS FILE IS AUTOMATICALLY GENERATED
# Do not edit this file. It will be overwritten when the configure script is run.
###


######
# Build ID: f5f48cdc
######

f5f48cdc_dirs_0 = .csconfig/f5f48cdc/obj
f5f48cdc_objs_0 = .csconfig/f5f48cdc/obj/cache.o\
  .csconfig/f5f48cdc/obj/cache_queues.o\
  .csconfig/f5f48cdc/obj/champsim.o\
  .csconfig/f5f48cdc/obj/dram_controller.o\
  .csconfig/f5f48cdc/obj/json_printer.o\
  .csconfig/f5f48cdc/obj/main.o\
  .csconfig/f5f48cdc/obj/module_defs.o\
  .csconfig/f5f48cdc/obj/ooo_cpu.o\
  .csconfig/f5f48cdc/obj/plain_printer.o\
  .csconfig/f5f48cdc/obj/ptw.o\
  .csconfig/f5f48cdc/obj/tracereader.o\
  .csconfig/f5f48cdc/obj/vmem.o
$(f5f48cdc_objs_0): .csconfig/f5f48cdc/obj/%.o: src/%.cc | $(f5f48cdc_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/obj/*.d))

$(f5f48cdc_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
bin/champsim: $(f5f48cdc_objs_0)
build_dirs += $(f5f48cdc_dirs_0)
build_objs += $(f5f48cdc_objs_0)
bin/champsim: | bin
build_dirs += bin
executable_name += bin/champsim

###
# Build ID: f5f48cdc
# Module: btbDbasic_btb
# Source: btb/basic_btb
# Destination: .csconfig/f5f48cdc/btbDbasic_btb
###

f5f48cdc_btbDbasic_btb_dirs_0 = .csconfig/f5f48cdc/btbDbasic_btb
f5f48cdc_btbDbasic_btb_objs_0 = .csconfig/f5f48cdc/btbDbasic_btb/basic_btb.o
$(f5f48cdc_btbDbasic_btb_objs_0): .csconfig/f5f48cdc/btbDbasic_btb/%.o: btb/basic_btb/%.cc | $(f5f48cdc_btbDbasic_btb_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/btbDbasic_btb/*.d))

$(f5f48cdc_btbDbasic_btb_objs_0): CPPFLAGS += -Ibtb/basic_btb
$(f5f48cdc_btbDbasic_btb_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_btbDbasic_btb_objs_0): CPPFLAGS += -include btbDbasic_btb.inc
$(f5f48cdc_btbDbasic_btb_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_btbDbasic_btb_objs_0)
module_dirs += $(f5f48cdc_btbDbasic_btb_dirs_0)
module_objs += $(f5f48cdc_btbDbasic_btb_objs_0)

###
# Build ID: f5f48cdc
# Module: btbDittage_64KB
# Source: btb/ittage_64KB
# Destination: .csconfig/f5f48cdc/btbDittage_64KB
###

f5f48cdc_btbDittage_64KB_dirs_0 = .csconfig/f5f48cdc/btbDittage_64KB
f5f48cdc_btbDittage_64KB_objs_0 = .csconfig/f5f48cdc/btbDittage_64KB/basic_btb.o
$(f5f48cdc_btbDittage_64KB_objs_0): .csconfig/f5f48cdc/btbDittage_64KB/%.o: btb/ittage_64KB/%.cc | $(f5f48cdc_btbDittage_64KB_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/btbDittage_64KB/*.d))

$(f5f48cdc_btbDittage_64KB_objs_0): CPPFLAGS += -Ibtb/ittage_64KB
$(f5f48cdc_btbDittage_64KB_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_btbDittage_64KB_objs_0): CPPFLAGS += -include btbDittage_64KB.inc
$(f5f48cdc_btbDittage_64KB_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_btbDittage_64KB_objs_0)
module_dirs += $(f5f48cdc_btbDittage_64KB_dirs_0)
module_objs += $(f5f48cdc_btbDittage_64KB_objs_0)

###
# Build ID: f5f48cdc
# Module: btbDtwolevel_btb_1Ke_32Ke_gshare_ittage
# Source: btb/twolevel_btb_1Ke_32Ke_gshare_ittage
# Destination: .csconfig/f5f48cdc/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage
###

f5f48cdc_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_dirs_0 = .csconfig/f5f48cdc/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage
f5f48cdc_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0 = .csconfig/f5f48cdc/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage/target_predictor.o
$(f5f48cdc_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): .csconfig/f5f48cdc/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage/%.o: btb/twolevel_btb_1Ke_32Ke_gshare_ittage/%.cc | $(f5f48cdc_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage/*.d))

$(f5f48cdc_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): CPPFLAGS += -Ibtb/twolevel_btb_1Ke_32Ke_gshare_ittage
$(f5f48cdc_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): CPPFLAGS += -include btbDtwolevel_btb_1Ke_32Ke_gshare_ittage.inc
$(f5f48cdc_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0)
module_dirs += $(f5f48cdc_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_dirs_0)
module_objs += $(f5f48cdc_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0)

###
# Build ID: f5f48cdc
# Module: branchDbatage
# Source: branch/batage
# Destination: .csconfig/f5f48cdc/branchDbatage
###

f5f48cdc_branchDbatage_dirs_0 = .csconfig/f5f48cdc/branchDbatage
f5f48cdc_branchDbatage_objs_0 = .csconfig/f5f48cdc/branchDbatage/batage.o\
  .csconfig/f5f48cdc/branchDbatage/btage_predictor.o
$(f5f48cdc_branchDbatage_objs_0): .csconfig/f5f48cdc/branchDbatage/%.o: branch/batage/%.cc | $(f5f48cdc_branchDbatage_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/branchDbatage/*.d))

$(f5f48cdc_branchDbatage_objs_0): CPPFLAGS += -Ibranch/batage
$(f5f48cdc_branchDbatage_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_branchDbatage_objs_0): CPPFLAGS += -include branchDbatage.inc
$(f5f48cdc_branchDbatage_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_branchDbatage_objs_0)
module_dirs += $(f5f48cdc_branchDbatage_dirs_0)
module_objs += $(f5f48cdc_branchDbatage_objs_0)

###
# Build ID: f5f48cdc
# Module: branchDbimodal
# Source: branch/bimodal
# Destination: .csconfig/f5f48cdc/branchDbimodal
###

f5f48cdc_branchDbimodal_dirs_0 = .csconfig/f5f48cdc/branchDbimodal
f5f48cdc_branchDbimodal_objs_0 = .csconfig/f5f48cdc/branchDbimodal/bimodal.o
$(f5f48cdc_branchDbimodal_objs_0): .csconfig/f5f48cdc/branchDbimodal/%.o: branch/bimodal/%.cc | $(f5f48cdc_branchDbimodal_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/branchDbimodal/*.d))

$(f5f48cdc_branchDbimodal_objs_0): CPPFLAGS += -Ibranch/bimodal
$(f5f48cdc_branchDbimodal_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_branchDbimodal_objs_0): CPPFLAGS += -include branchDbimodal.inc
$(f5f48cdc_branchDbimodal_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_branchDbimodal_objs_0)
module_dirs += $(f5f48cdc_branchDbimodal_dirs_0)
module_objs += $(f5f48cdc_branchDbimodal_objs_0)

###
# Build ID: f5f48cdc
# Module: branchDgshare
# Source: branch/gshare
# Destination: .csconfig/f5f48cdc/branchDgshare
###

f5f48cdc_branchDgshare_dirs_0 = .csconfig/f5f48cdc/branchDgshare
f5f48cdc_branchDgshare_objs_0 = .csconfig/f5f48cdc/branchDgshare/gshare.o
$(f5f48cdc_branchDgshare_objs_0): .csconfig/f5f48cdc/branchDgshare/%.o: branch/gshare/%.cc | $(f5f48cdc_branchDgshare_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/branchDgshare/*.d))

$(f5f48cdc_branchDgshare_objs_0): CPPFLAGS += -Ibranch/gshare
$(f5f48cdc_branchDgshare_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_branchDgshare_objs_0): CPPFLAGS += -include branchDgshare.inc
$(f5f48cdc_branchDgshare_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_branchDgshare_objs_0)
module_dirs += $(f5f48cdc_branchDgshare_dirs_0)
module_objs += $(f5f48cdc_branchDgshare_objs_0)

###
# Build ID: f5f48cdc
# Module: branchDhashed_perceptron
# Source: branch/hashed_perceptron
# Destination: .csconfig/f5f48cdc/branchDhashed_perceptron
###

f5f48cdc_branchDhashed_perceptron_dirs_0 = .csconfig/f5f48cdc/branchDhashed_perceptron
f5f48cdc_branchDhashed_perceptron_objs_0 = .csconfig/f5f48cdc/branchDhashed_perceptron/hashed_perceptron.o
$(f5f48cdc_branchDhashed_perceptron_objs_0): .csconfig/f5f48cdc/branchDhashed_perceptron/%.o: branch/hashed_perceptron/%.cc | $(f5f48cdc_branchDhashed_perceptron_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/branchDhashed_perceptron/*.d))

$(f5f48cdc_branchDhashed_perceptron_objs_0): CPPFLAGS += -Ibranch/hashed_perceptron
$(f5f48cdc_branchDhashed_perceptron_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_branchDhashed_perceptron_objs_0): CPPFLAGS += -include branchDhashed_perceptron.inc
$(f5f48cdc_branchDhashed_perceptron_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_branchDhashed_perceptron_objs_0)
module_dirs += $(f5f48cdc_branchDhashed_perceptron_dirs_0)
module_objs += $(f5f48cdc_branchDhashed_perceptron_objs_0)

###
# Build ID: f5f48cdc
# Module: branchDperceptron
# Source: branch/perceptron
# Destination: .csconfig/f5f48cdc/branchDperceptron
###

f5f48cdc_branchDperceptron_dirs_0 = .csconfig/f5f48cdc/branchDperceptron
f5f48cdc_branchDperceptron_objs_0 = .csconfig/f5f48cdc/branchDperceptron/perceptron.o
$(f5f48cdc_branchDperceptron_objs_0): .csconfig/f5f48cdc/branchDperceptron/%.o: branch/perceptron/%.cc | $(f5f48cdc_branchDperceptron_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/branchDperceptron/*.d))

$(f5f48cdc_branchDperceptron_objs_0): CPPFLAGS += -Ibranch/perceptron
$(f5f48cdc_branchDperceptron_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_branchDperceptron_objs_0): CPPFLAGS += -include branchDperceptron.inc
$(f5f48cdc_branchDperceptron_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_branchDperceptron_objs_0)
module_dirs += $(f5f48cdc_branchDperceptron_dirs_0)
module_objs += $(f5f48cdc_branchDperceptron_objs_0)

###
# Build ID: f5f48cdc
# Module: branchDtage_sc_l
# Source: branch/tage_sc_l
# Destination: .csconfig/f5f48cdc/branchDtage_sc_l
###

f5f48cdc_branchDtage_sc_l_dirs_0 = .csconfig/f5f48cdc/branchDtage_sc_l
f5f48cdc_branchDtage_sc_l_objs_0 = .csconfig/f5f48cdc/branchDtage_sc_l/tage_sc_l.o
$(f5f48cdc_branchDtage_sc_l_objs_0): .csconfig/f5f48cdc/branchDtage_sc_l/%.o: branch/tage_sc_l/%.cc | $(f5f48cdc_branchDtage_sc_l_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/branchDtage_sc_l/*.d))

$(f5f48cdc_branchDtage_sc_l_objs_0): CPPFLAGS += -Ibranch/tage_sc_l
$(f5f48cdc_branchDtage_sc_l_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_branchDtage_sc_l_objs_0): CPPFLAGS += -include branchDtage_sc_l.inc
$(f5f48cdc_branchDtage_sc_l_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_branchDtage_sc_l_objs_0)
module_dirs += $(f5f48cdc_branchDtage_sc_l_dirs_0)
module_objs += $(f5f48cdc_branchDtage_sc_l_objs_0)

###
# Build ID: f5f48cdc
# Module: prefetcherDDHJOLT_instr
# Source: prefetcher/D-JOLT_instr
# Destination: .csconfig/f5f48cdc/prefetcherDDHJOLT_instr
###

f5f48cdc_prefetcherDDHJOLT_instr_dirs_0 = .csconfig/f5f48cdc/prefetcherDDHJOLT_instr
f5f48cdc_prefetcherDDHJOLT_instr_objs_0 = .csconfig/f5f48cdc/prefetcherDDHJOLT_instr/d_jolt.o
$(f5f48cdc_prefetcherDDHJOLT_instr_objs_0): .csconfig/f5f48cdc/prefetcherDDHJOLT_instr/%.o: prefetcher/D-JOLT_instr/%.cc | $(f5f48cdc_prefetcherDDHJOLT_instr_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/prefetcherDDHJOLT_instr/*.d))

$(f5f48cdc_prefetcherDDHJOLT_instr_objs_0): CPPFLAGS += -Iprefetcher/D-JOLT_instr
$(f5f48cdc_prefetcherDDHJOLT_instr_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_prefetcherDDHJOLT_instr_objs_0): CPPFLAGS += -include prefetcherDDHJOLT_instr.inc
$(f5f48cdc_prefetcherDDHJOLT_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_prefetcherDDHJOLT_instr_objs_0)
module_dirs += $(f5f48cdc_prefetcherDDHJOLT_instr_dirs_0)
module_objs += $(f5f48cdc_prefetcherDDHJOLT_instr_objs_0)

###
# Build ID: f5f48cdc
# Module: prefetcherDFNLHMMA_instr
# Source: prefetcher/FNL-MMA_instr
# Destination: .csconfig/f5f48cdc/prefetcherDFNLHMMA_instr
###

f5f48cdc_prefetcherDFNLHMMA_instr_dirs_0 = .csconfig/f5f48cdc/prefetcherDFNLHMMA_instr
f5f48cdc_prefetcherDFNLHMMA_instr_objs_0 = .csconfig/f5f48cdc/prefetcherDFNLHMMA_instr/fnl_mma.o
$(f5f48cdc_prefetcherDFNLHMMA_instr_objs_0): .csconfig/f5f48cdc/prefetcherDFNLHMMA_instr/%.o: prefetcher/FNL-MMA_instr/%.cc | $(f5f48cdc_prefetcherDFNLHMMA_instr_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/prefetcherDFNLHMMA_instr/*.d))

$(f5f48cdc_prefetcherDFNLHMMA_instr_objs_0): CPPFLAGS += -Iprefetcher/FNL-MMA_instr
$(f5f48cdc_prefetcherDFNLHMMA_instr_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_prefetcherDFNLHMMA_instr_objs_0): CPPFLAGS += -include prefetcherDFNLHMMA_instr.inc
$(f5f48cdc_prefetcherDFNLHMMA_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_prefetcherDFNLHMMA_instr_objs_0)
module_dirs += $(f5f48cdc_prefetcherDFNLHMMA_instr_dirs_0)
module_objs += $(f5f48cdc_prefetcherDFNLHMMA_instr_objs_0)

###
# Build ID: f5f48cdc
# Module: prefetcherDISCA_Entangling_4Ke_instr
# Source: prefetcher/ISCA_Entangling_4Ke_instr
# Destination: .csconfig/f5f48cdc/prefetcherDISCA_Entangling_4Ke_instr
###

f5f48cdc_prefetcherDISCA_Entangling_4Ke_instr_dirs_0 = .csconfig/f5f48cdc/prefetcherDISCA_Entangling_4Ke_instr
f5f48cdc_prefetcherDISCA_Entangling_4Ke_instr_objs_0 = .csconfig/f5f48cdc/prefetcherDISCA_Entangling_4Ke_instr/ISCA_Entangling_4Ke.o
$(f5f48cdc_prefetcherDISCA_Entangling_4Ke_instr_objs_0): .csconfig/f5f48cdc/prefetcherDISCA_Entangling_4Ke_instr/%.o: prefetcher/ISCA_Entangling_4Ke_instr/%.cc | $(f5f48cdc_prefetcherDISCA_Entangling_4Ke_instr_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/prefetcherDISCA_Entangling_4Ke_instr/*.d))

$(f5f48cdc_prefetcherDISCA_Entangling_4Ke_instr_objs_0): CPPFLAGS += -Iprefetcher/ISCA_Entangling_4Ke_instr
$(f5f48cdc_prefetcherDISCA_Entangling_4Ke_instr_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_prefetcherDISCA_Entangling_4Ke_instr_objs_0): CPPFLAGS += -include prefetcherDISCA_Entangling_4Ke_instr.inc
$(f5f48cdc_prefetcherDISCA_Entangling_4Ke_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_prefetcherDISCA_Entangling_4Ke_instr_objs_0)
module_dirs += $(f5f48cdc_prefetcherDISCA_Entangling_4Ke_instr_dirs_0)
module_objs += $(f5f48cdc_prefetcherDISCA_Entangling_4Ke_instr_objs_0)

###
# Build ID: f5f48cdc
# Module: prefetcherDip_stride
# Source: prefetcher/ip_stride
# Destination: .csconfig/f5f48cdc/prefetcherDip_stride
###

f5f48cdc_prefetcherDip_stride_dirs_0 = .csconfig/f5f48cdc/prefetcherDip_stride
f5f48cdc_prefetcherDip_stride_objs_0 = .csconfig/f5f48cdc/prefetcherDip_stride/ip_stride.o
$(f5f48cdc_prefetcherDip_stride_objs_0): .csconfig/f5f48cdc/prefetcherDip_stride/%.o: prefetcher/ip_stride/%.cc | $(f5f48cdc_prefetcherDip_stride_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/prefetcherDip_stride/*.d))

$(f5f48cdc_prefetcherDip_stride_objs_0): CPPFLAGS += -Iprefetcher/ip_stride
$(f5f48cdc_prefetcherDip_stride_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_prefetcherDip_stride_objs_0): CPPFLAGS += -include prefetcherDip_stride.inc
$(f5f48cdc_prefetcherDip_stride_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_prefetcherDip_stride_objs_0)
module_dirs += $(f5f48cdc_prefetcherDip_stride_dirs_0)
module_objs += $(f5f48cdc_prefetcherDip_stride_objs_0)

###
# Build ID: f5f48cdc
# Module: prefetcherDmini_djolt_instr
# Source: prefetcher/mini_djolt_instr
# Destination: .csconfig/f5f48cdc/prefetcherDmini_djolt_instr
###

f5f48cdc_prefetcherDmini_djolt_instr_dirs_0 = .csconfig/f5f48cdc/prefetcherDmini_djolt_instr
f5f48cdc_prefetcherDmini_djolt_instr_objs_0 = .csconfig/f5f48cdc/prefetcherDmini_djolt_instr/mini_djolt.o
$(f5f48cdc_prefetcherDmini_djolt_instr_objs_0): .csconfig/f5f48cdc/prefetcherDmini_djolt_instr/%.o: prefetcher/mini_djolt_instr/%.cc | $(f5f48cdc_prefetcherDmini_djolt_instr_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/prefetcherDmini_djolt_instr/*.d))

$(f5f48cdc_prefetcherDmini_djolt_instr_objs_0): CPPFLAGS += -Iprefetcher/mini_djolt_instr
$(f5f48cdc_prefetcherDmini_djolt_instr_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_prefetcherDmini_djolt_instr_objs_0): CPPFLAGS += -include prefetcherDmini_djolt_instr.inc
$(f5f48cdc_prefetcherDmini_djolt_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_prefetcherDmini_djolt_instr_objs_0)
module_dirs += $(f5f48cdc_prefetcherDmini_djolt_instr_dirs_0)
module_objs += $(f5f48cdc_prefetcherDmini_djolt_instr_objs_0)

###
# Build ID: f5f48cdc
# Module: prefetcherDnext_line
# Source: prefetcher/next_line
# Destination: .csconfig/f5f48cdc/prefetcherDnext_line
###

f5f48cdc_prefetcherDnext_line_dirs_0 = .csconfig/f5f48cdc/prefetcherDnext_line
f5f48cdc_prefetcherDnext_line_objs_0 = .csconfig/f5f48cdc/prefetcherDnext_line/next_line.o
$(f5f48cdc_prefetcherDnext_line_objs_0): .csconfig/f5f48cdc/prefetcherDnext_line/%.o: prefetcher/next_line/%.cc | $(f5f48cdc_prefetcherDnext_line_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/prefetcherDnext_line/*.d))

$(f5f48cdc_prefetcherDnext_line_objs_0): CPPFLAGS += -Iprefetcher/next_line
$(f5f48cdc_prefetcherDnext_line_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_prefetcherDnext_line_objs_0): CPPFLAGS += -include prefetcherDnext_line.inc
$(f5f48cdc_prefetcherDnext_line_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_prefetcherDnext_line_objs_0)
module_dirs += $(f5f48cdc_prefetcherDnext_line_dirs_0)
module_objs += $(f5f48cdc_prefetcherDnext_line_objs_0)

###
# Build ID: f5f48cdc
# Module: prefetcherDnext_line_instr
# Source: prefetcher/next_line_instr
# Destination: .csconfig/f5f48cdc/prefetcherDnext_line_instr
###

f5f48cdc_prefetcherDnext_line_instr_dirs_0 = .csconfig/f5f48cdc/prefetcherDnext_line_instr
f5f48cdc_prefetcherDnext_line_instr_objs_0 = .csconfig/f5f48cdc/prefetcherDnext_line_instr/next_line.o
$(f5f48cdc_prefetcherDnext_line_instr_objs_0): .csconfig/f5f48cdc/prefetcherDnext_line_instr/%.o: prefetcher/next_line_instr/%.cc | $(f5f48cdc_prefetcherDnext_line_instr_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/prefetcherDnext_line_instr/*.d))

$(f5f48cdc_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -Iprefetcher/next_line_instr
$(f5f48cdc_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -include prefetcherDnext_line_instr.inc
$(f5f48cdc_prefetcherDnext_line_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_prefetcherDnext_line_instr_objs_0)
module_dirs += $(f5f48cdc_prefetcherDnext_line_instr_dirs_0)
module_objs += $(f5f48cdc_prefetcherDnext_line_instr_objs_0)

###
# Build ID: f5f48cdc
# Module: prefetcherDno
# Source: prefetcher/no
# Destination: .csconfig/f5f48cdc/prefetcherDno
###

f5f48cdc_prefetcherDno_dirs_0 = .csconfig/f5f48cdc/prefetcherDno
f5f48cdc_prefetcherDno_objs_0 = .csconfig/f5f48cdc/prefetcherDno/no.o
$(f5f48cdc_prefetcherDno_objs_0): .csconfig/f5f48cdc/prefetcherDno/%.o: prefetcher/no/%.cc | $(f5f48cdc_prefetcherDno_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/prefetcherDno/*.d))

$(f5f48cdc_prefetcherDno_objs_0): CPPFLAGS += -Iprefetcher/no
$(f5f48cdc_prefetcherDno_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_prefetcherDno_objs_0): CPPFLAGS += -include prefetcherDno.inc
$(f5f48cdc_prefetcherDno_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_prefetcherDno_objs_0)
module_dirs += $(f5f48cdc_prefetcherDno_dirs_0)
module_objs += $(f5f48cdc_prefetcherDno_objs_0)

###
# Build ID: f5f48cdc
# Module: prefetcherDno_instr
# Source: prefetcher/no_instr
# Destination: .csconfig/f5f48cdc/prefetcherDno_instr
###

f5f48cdc_prefetcherDno_instr_dirs_0 = .csconfig/f5f48cdc/prefetcherDno_instr
f5f48cdc_prefetcherDno_instr_objs_0 = .csconfig/f5f48cdc/prefetcherDno_instr/no.o
$(f5f48cdc_prefetcherDno_instr_objs_0): .csconfig/f5f48cdc/prefetcherDno_instr/%.o: prefetcher/no_instr/%.cc | $(f5f48cdc_prefetcherDno_instr_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/prefetcherDno_instr/*.d))

$(f5f48cdc_prefetcherDno_instr_objs_0): CPPFLAGS += -Iprefetcher/no_instr
$(f5f48cdc_prefetcherDno_instr_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_prefetcherDno_instr_objs_0): CPPFLAGS += -include prefetcherDno_instr.inc
$(f5f48cdc_prefetcherDno_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_prefetcherDno_instr_objs_0)
module_dirs += $(f5f48cdc_prefetcherDno_instr_dirs_0)
module_objs += $(f5f48cdc_prefetcherDno_instr_objs_0)

###
# Build ID: f5f48cdc
# Module: prefetcherDspp_dev
# Source: prefetcher/spp_dev
# Destination: .csconfig/f5f48cdc/prefetcherDspp_dev
###

f5f48cdc_prefetcherDspp_dev_dirs_0 = .csconfig/f5f48cdc/prefetcherDspp_dev
f5f48cdc_prefetcherDspp_dev_objs_0 = .csconfig/f5f48cdc/prefetcherDspp_dev/spp_dev.o
$(f5f48cdc_prefetcherDspp_dev_objs_0): .csconfig/f5f48cdc/prefetcherDspp_dev/%.o: prefetcher/spp_dev/%.cc | $(f5f48cdc_prefetcherDspp_dev_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/prefetcherDspp_dev/*.d))

$(f5f48cdc_prefetcherDspp_dev_objs_0): CPPFLAGS += -Iprefetcher/spp_dev
$(f5f48cdc_prefetcherDspp_dev_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_prefetcherDspp_dev_objs_0): CPPFLAGS += -include prefetcherDspp_dev.inc
$(f5f48cdc_prefetcherDspp_dev_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_prefetcherDspp_dev_objs_0)
module_dirs += $(f5f48cdc_prefetcherDspp_dev_dirs_0)
module_objs += $(f5f48cdc_prefetcherDspp_dev_objs_0)

###
# Build ID: f5f48cdc
# Module: prefetcherDva_ampm_lite
# Source: prefetcher/va_ampm_lite
# Destination: .csconfig/f5f48cdc/prefetcherDva_ampm_lite
###

f5f48cdc_prefetcherDva_ampm_lite_dirs_0 = .csconfig/f5f48cdc/prefetcherDva_ampm_lite
f5f48cdc_prefetcherDva_ampm_lite_objs_0 = .csconfig/f5f48cdc/prefetcherDva_ampm_lite/va_ampm_lite.o
$(f5f48cdc_prefetcherDva_ampm_lite_objs_0): .csconfig/f5f48cdc/prefetcherDva_ampm_lite/%.o: prefetcher/va_ampm_lite/%.cc | $(f5f48cdc_prefetcherDva_ampm_lite_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/prefetcherDva_ampm_lite/*.d))

$(f5f48cdc_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -Iprefetcher/va_ampm_lite
$(f5f48cdc_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -include prefetcherDva_ampm_lite.inc
$(f5f48cdc_prefetcherDva_ampm_lite_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_prefetcherDva_ampm_lite_objs_0)
module_dirs += $(f5f48cdc_prefetcherDva_ampm_lite_dirs_0)
module_objs += $(f5f48cdc_prefetcherDva_ampm_lite_objs_0)

###
# Build ID: f5f48cdc
# Module: replacementDdrrip
# Source: replacement/drrip
# Destination: .csconfig/f5f48cdc/replacementDdrrip
###

f5f48cdc_replacementDdrrip_dirs_0 = .csconfig/f5f48cdc/replacementDdrrip
f5f48cdc_replacementDdrrip_objs_0 = .csconfig/f5f48cdc/replacementDdrrip/drrip.o
$(f5f48cdc_replacementDdrrip_objs_0): .csconfig/f5f48cdc/replacementDdrrip/%.o: replacement/drrip/%.cc | $(f5f48cdc_replacementDdrrip_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/replacementDdrrip/*.d))

$(f5f48cdc_replacementDdrrip_objs_0): CPPFLAGS += -Ireplacement/drrip
$(f5f48cdc_replacementDdrrip_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_replacementDdrrip_objs_0): CPPFLAGS += -include replacementDdrrip.inc
$(f5f48cdc_replacementDdrrip_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_replacementDdrrip_objs_0)
module_dirs += $(f5f48cdc_replacementDdrrip_dirs_0)
module_objs += $(f5f48cdc_replacementDdrrip_objs_0)

###
# Build ID: f5f48cdc
# Module: replacementDhotloop
# Source: replacement/hotloop
# Destination: .csconfig/f5f48cdc/replacementDhotloop
###

f5f48cdc_replacementDhotloop_dirs_0 = .csconfig/f5f48cdc/replacementDhotloop
f5f48cdc_replacementDhotloop_objs_0 = .csconfig/f5f48cdc/replacementDhotloop/hotloop.o
$(f5f48cdc_replacementDhotloop_objs_0): .csconfig/f5f48cdc/replacementDhotloop/%.o: replacement/hotloop/%.cc | $(f5f48cdc_replacementDhotloop_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/replacementDhotloop/*.d))

$(f5f48cdc_replacementDhotloop_objs_0): CPPFLAGS += -Ireplacement/hotloop
$(f5f48cdc_replacementDhotloop_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_replacementDhotloop_objs_0): CPPFLAGS += -include replacementDhotloop.inc
$(f5f48cdc_replacementDhotloop_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_replacementDhotloop_objs_0)
module_dirs += $(f5f48cdc_replacementDhotloop_dirs_0)
module_objs += $(f5f48cdc_replacementDhotloop_objs_0)

###
# Build ID: f5f48cdc
# Module: replacementDhotloop_lru
# Source: replacement/hotloop_lru
# Destination: .csconfig/f5f48cdc/replacementDhotloop_lru
###

f5f48cdc_replacementDhotloop_lru_dirs_0 = .csconfig/f5f48cdc/replacementDhotloop_lru
f5f48cdc_replacementDhotloop_lru_objs_0 = .csconfig/f5f48cdc/replacementDhotloop_lru/hotloop_lru.o
$(f5f48cdc_replacementDhotloop_lru_objs_0): .csconfig/f5f48cdc/replacementDhotloop_lru/%.o: replacement/hotloop_lru/%.cc | $(f5f48cdc_replacementDhotloop_lru_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/replacementDhotloop_lru/*.d))

$(f5f48cdc_replacementDhotloop_lru_objs_0): CPPFLAGS += -Ireplacement/hotloop_lru
$(f5f48cdc_replacementDhotloop_lru_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_replacementDhotloop_lru_objs_0): CPPFLAGS += -include replacementDhotloop_lru.inc
$(f5f48cdc_replacementDhotloop_lru_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_replacementDhotloop_lru_objs_0)
module_dirs += $(f5f48cdc_replacementDhotloop_lru_dirs_0)
module_objs += $(f5f48cdc_replacementDhotloop_lru_objs_0)

###
# Build ID: f5f48cdc
# Module: replacementDlru
# Source: replacement/lru
# Destination: .csconfig/f5f48cdc/replacementDlru
###

f5f48cdc_replacementDlru_dirs_0 = .csconfig/f5f48cdc/replacementDlru
f5f48cdc_replacementDlru_objs_0 = .csconfig/f5f48cdc/replacementDlru/lru.o
$(f5f48cdc_replacementDlru_objs_0): .csconfig/f5f48cdc/replacementDlru/%.o: replacement/lru/%.cc | $(f5f48cdc_replacementDlru_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/replacementDlru/*.d))

$(f5f48cdc_replacementDlru_objs_0): CPPFLAGS += -Ireplacement/lru
$(f5f48cdc_replacementDlru_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_replacementDlru_objs_0): CPPFLAGS += -include replacementDlru.inc
$(f5f48cdc_replacementDlru_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_replacementDlru_objs_0)
module_dirs += $(f5f48cdc_replacementDlru_dirs_0)
module_objs += $(f5f48cdc_replacementDlru_objs_0)

###
# Build ID: f5f48cdc
# Module: replacementDship
# Source: replacement/ship
# Destination: .csconfig/f5f48cdc/replacementDship
###

f5f48cdc_replacementDship_dirs_0 = .csconfig/f5f48cdc/replacementDship
f5f48cdc_replacementDship_objs_0 = .csconfig/f5f48cdc/replacementDship/ship.o
$(f5f48cdc_replacementDship_objs_0): .csconfig/f5f48cdc/replacementDship/%.o: replacement/ship/%.cc | $(f5f48cdc_replacementDship_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/replacementDship/*.d))

$(f5f48cdc_replacementDship_objs_0): CPPFLAGS += -Ireplacement/ship
$(f5f48cdc_replacementDship_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_replacementDship_objs_0): CPPFLAGS += -include replacementDship.inc
$(f5f48cdc_replacementDship_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_replacementDship_objs_0)
module_dirs += $(f5f48cdc_replacementDship_dirs_0)
module_objs += $(f5f48cdc_replacementDship_objs_0)

###
# Build ID: f5f48cdc
# Module: replacementDsrrip
# Source: replacement/srrip
# Destination: .csconfig/f5f48cdc/replacementDsrrip
###

f5f48cdc_replacementDsrrip_dirs_0 = .csconfig/f5f48cdc/replacementDsrrip
f5f48cdc_replacementDsrrip_objs_0 = .csconfig/f5f48cdc/replacementDsrrip/srrip.o
$(f5f48cdc_replacementDsrrip_objs_0): .csconfig/f5f48cdc/replacementDsrrip/%.o: replacement/srrip/%.cc | $(f5f48cdc_replacementDsrrip_dirs_0)
-include $(wildcard .csconfig/f5f48cdc/replacementDsrrip/*.d))

$(f5f48cdc_replacementDsrrip_objs_0): CPPFLAGS += -Ireplacement/srrip
$(f5f48cdc_replacementDsrrip_objs_0): CPPFLAGS += -I.csconfig/f5f48cdc/inc
$(f5f48cdc_replacementDsrrip_objs_0): CPPFLAGS += -include replacementDsrrip.inc
$(f5f48cdc_replacementDsrrip_objs_0): CXXFLAGS += -Wno-unused-parameter
bin/champsim: $(f5f48cdc_replacementDsrrip_objs_0)
module_dirs += $(f5f48cdc_replacementDsrrip_dirs_0)
module_objs += $(f5f48cdc_replacementDsrrip_objs_0)

######
# Build ID: d6ee6fa2
######

d6ee6fa2_dirs_0 = .csconfig/test/d6ee6fa2/obj
d6ee6fa2_objs_0 = .csconfig/test/d6ee6fa2/obj/cache.o\
  .csconfig/test/d6ee6fa2/obj/cache_queues.o\
  .csconfig/test/d6ee6fa2/obj/champsim.o\
  .csconfig/test/d6ee6fa2/obj/dram_controller.o\
  .csconfig/test/d6ee6fa2/obj/json_printer.o\
  .csconfig/test/d6ee6fa2/obj/main.o\
  .csconfig/test/d6ee6fa2/obj/module_defs.o\
  .csconfig/test/d6ee6fa2/obj/ooo_cpu.o\
  .csconfig/test/d6ee6fa2/obj/plain_printer.o\
  .csconfig/test/d6ee6fa2/obj/ptw.o\
  .csconfig/test/d6ee6fa2/obj/tracereader.o\
  .csconfig/test/d6ee6fa2/obj/vmem.o
$(d6ee6fa2_objs_0): .csconfig/test/d6ee6fa2/obj/%.o: src/%.cc | $(d6ee6fa2_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/obj/*.d))

$(d6ee6fa2_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
test/bin/000-test-main: $(d6ee6fa2_objs_0)
build_dirs += $(d6ee6fa2_dirs_0)
build_objs += $(d6ee6fa2_objs_0)
test/bin/000-test-main: | test/bin
build_dirs += test/bin
executable_name += test/bin/000-test-main

###
# Build ID: d6ee6fa2
# Module: btbDbasic_btb
# Source: btb/basic_btb
# Destination: .csconfig/test/d6ee6fa2/btbDbasic_btb
###

d6ee6fa2_btbDbasic_btb_dirs_0 = .csconfig/test/d6ee6fa2/btbDbasic_btb
d6ee6fa2_btbDbasic_btb_objs_0 = .csconfig/test/d6ee6fa2/btbDbasic_btb/basic_btb.o
$(d6ee6fa2_btbDbasic_btb_objs_0): .csconfig/test/d6ee6fa2/btbDbasic_btb/%.o: btb/basic_btb/%.cc | $(d6ee6fa2_btbDbasic_btb_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/btbDbasic_btb/*.d))

$(d6ee6fa2_btbDbasic_btb_objs_0): CPPFLAGS += -Ibtb/basic_btb
$(d6ee6fa2_btbDbasic_btb_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_btbDbasic_btb_objs_0): CPPFLAGS += -include btbDbasic_btb.inc
$(d6ee6fa2_btbDbasic_btb_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_btbDbasic_btb_objs_0)
module_dirs += $(d6ee6fa2_btbDbasic_btb_dirs_0)
module_objs += $(d6ee6fa2_btbDbasic_btb_objs_0)

###
# Build ID: d6ee6fa2
# Module: btbDittage_64KB
# Source: btb/ittage_64KB
# Destination: .csconfig/test/d6ee6fa2/btbDittage_64KB
###

d6ee6fa2_btbDittage_64KB_dirs_0 = .csconfig/test/d6ee6fa2/btbDittage_64KB
d6ee6fa2_btbDittage_64KB_objs_0 = .csconfig/test/d6ee6fa2/btbDittage_64KB/basic_btb.o
$(d6ee6fa2_btbDittage_64KB_objs_0): .csconfig/test/d6ee6fa2/btbDittage_64KB/%.o: btb/ittage_64KB/%.cc | $(d6ee6fa2_btbDittage_64KB_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/btbDittage_64KB/*.d))

$(d6ee6fa2_btbDittage_64KB_objs_0): CPPFLAGS += -Ibtb/ittage_64KB
$(d6ee6fa2_btbDittage_64KB_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_btbDittage_64KB_objs_0): CPPFLAGS += -include btbDittage_64KB.inc
$(d6ee6fa2_btbDittage_64KB_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_btbDittage_64KB_objs_0)
module_dirs += $(d6ee6fa2_btbDittage_64KB_dirs_0)
module_objs += $(d6ee6fa2_btbDittage_64KB_objs_0)

###
# Build ID: d6ee6fa2
# Module: btbDtwolevel_btb_1Ke_32Ke_gshare_ittage
# Source: btb/twolevel_btb_1Ke_32Ke_gshare_ittage
# Destination: .csconfig/test/d6ee6fa2/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage
###

d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_dirs_0 = .csconfig/test/d6ee6fa2/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage
d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0 = .csconfig/test/d6ee6fa2/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage/target_predictor.o
$(d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): .csconfig/test/d6ee6fa2/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage/%.o: btb/twolevel_btb_1Ke_32Ke_gshare_ittage/%.cc | $(d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/btbDtwolevel_btb_1Ke_32Ke_gshare_ittage/*.d))

$(d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): CPPFLAGS += -Ibtb/twolevel_btb_1Ke_32Ke_gshare_ittage
$(d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): CPPFLAGS += -include btbDtwolevel_btb_1Ke_32Ke_gshare_ittage.inc
$(d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0)
module_dirs += $(d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_dirs_0)
module_objs += $(d6ee6fa2_btbDtwolevel_btb_1Ke_32Ke_gshare_ittage_objs_0)

###
# Build ID: d6ee6fa2
# Module: branchDbatage
# Source: branch/batage
# Destination: .csconfig/test/d6ee6fa2/branchDbatage
###

d6ee6fa2_branchDbatage_dirs_0 = .csconfig/test/d6ee6fa2/branchDbatage
d6ee6fa2_branchDbatage_objs_0 = .csconfig/test/d6ee6fa2/branchDbatage/batage.o\
  .csconfig/test/d6ee6fa2/branchDbatage/btage_predictor.o
$(d6ee6fa2_branchDbatage_objs_0): .csconfig/test/d6ee6fa2/branchDbatage/%.o: branch/batage/%.cc | $(d6ee6fa2_branchDbatage_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/branchDbatage/*.d))

$(d6ee6fa2_branchDbatage_objs_0): CPPFLAGS += -Ibranch/batage
$(d6ee6fa2_branchDbatage_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_branchDbatage_objs_0): CPPFLAGS += -include branchDbatage.inc
$(d6ee6fa2_branchDbatage_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_branchDbatage_objs_0)
module_dirs += $(d6ee6fa2_branchDbatage_dirs_0)
module_objs += $(d6ee6fa2_branchDbatage_objs_0)

###
# Build ID: d6ee6fa2
# Module: branchDbimodal
# Source: branch/bimodal
# Destination: .csconfig/test/d6ee6fa2/branchDbimodal
###

d6ee6fa2_branchDbimodal_dirs_0 = .csconfig/test/d6ee6fa2/branchDbimodal
d6ee6fa2_branchDbimodal_objs_0 = .csconfig/test/d6ee6fa2/branchDbimodal/bimodal.o
$(d6ee6fa2_branchDbimodal_objs_0): .csconfig/test/d6ee6fa2/branchDbimodal/%.o: branch/bimodal/%.cc | $(d6ee6fa2_branchDbimodal_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/branchDbimodal/*.d))

$(d6ee6fa2_branchDbimodal_objs_0): CPPFLAGS += -Ibranch/bimodal
$(d6ee6fa2_branchDbimodal_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_branchDbimodal_objs_0): CPPFLAGS += -include branchDbimodal.inc
$(d6ee6fa2_branchDbimodal_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_branchDbimodal_objs_0)
module_dirs += $(d6ee6fa2_branchDbimodal_dirs_0)
module_objs += $(d6ee6fa2_branchDbimodal_objs_0)

###
# Build ID: d6ee6fa2
# Module: branchDgshare
# Source: branch/gshare
# Destination: .csconfig/test/d6ee6fa2/branchDgshare
###

d6ee6fa2_branchDgshare_dirs_0 = .csconfig/test/d6ee6fa2/branchDgshare
d6ee6fa2_branchDgshare_objs_0 = .csconfig/test/d6ee6fa2/branchDgshare/gshare.o
$(d6ee6fa2_branchDgshare_objs_0): .csconfig/test/d6ee6fa2/branchDgshare/%.o: branch/gshare/%.cc | $(d6ee6fa2_branchDgshare_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/branchDgshare/*.d))

$(d6ee6fa2_branchDgshare_objs_0): CPPFLAGS += -Ibranch/gshare
$(d6ee6fa2_branchDgshare_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_branchDgshare_objs_0): CPPFLAGS += -include branchDgshare.inc
$(d6ee6fa2_branchDgshare_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_branchDgshare_objs_0)
module_dirs += $(d6ee6fa2_branchDgshare_dirs_0)
module_objs += $(d6ee6fa2_branchDgshare_objs_0)

###
# Build ID: d6ee6fa2
# Module: branchDhashed_perceptron
# Source: branch/hashed_perceptron
# Destination: .csconfig/test/d6ee6fa2/branchDhashed_perceptron
###

d6ee6fa2_branchDhashed_perceptron_dirs_0 = .csconfig/test/d6ee6fa2/branchDhashed_perceptron
d6ee6fa2_branchDhashed_perceptron_objs_0 = .csconfig/test/d6ee6fa2/branchDhashed_perceptron/hashed_perceptron.o
$(d6ee6fa2_branchDhashed_perceptron_objs_0): .csconfig/test/d6ee6fa2/branchDhashed_perceptron/%.o: branch/hashed_perceptron/%.cc | $(d6ee6fa2_branchDhashed_perceptron_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/branchDhashed_perceptron/*.d))

$(d6ee6fa2_branchDhashed_perceptron_objs_0): CPPFLAGS += -Ibranch/hashed_perceptron
$(d6ee6fa2_branchDhashed_perceptron_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_branchDhashed_perceptron_objs_0): CPPFLAGS += -include branchDhashed_perceptron.inc
$(d6ee6fa2_branchDhashed_perceptron_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_branchDhashed_perceptron_objs_0)
module_dirs += $(d6ee6fa2_branchDhashed_perceptron_dirs_0)
module_objs += $(d6ee6fa2_branchDhashed_perceptron_objs_0)

###
# Build ID: d6ee6fa2
# Module: branchDperceptron
# Source: branch/perceptron
# Destination: .csconfig/test/d6ee6fa2/branchDperceptron
###

d6ee6fa2_branchDperceptron_dirs_0 = .csconfig/test/d6ee6fa2/branchDperceptron
d6ee6fa2_branchDperceptron_objs_0 = .csconfig/test/d6ee6fa2/branchDperceptron/perceptron.o
$(d6ee6fa2_branchDperceptron_objs_0): .csconfig/test/d6ee6fa2/branchDperceptron/%.o: branch/perceptron/%.cc | $(d6ee6fa2_branchDperceptron_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/branchDperceptron/*.d))

$(d6ee6fa2_branchDperceptron_objs_0): CPPFLAGS += -Ibranch/perceptron
$(d6ee6fa2_branchDperceptron_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_branchDperceptron_objs_0): CPPFLAGS += -include branchDperceptron.inc
$(d6ee6fa2_branchDperceptron_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_branchDperceptron_objs_0)
module_dirs += $(d6ee6fa2_branchDperceptron_dirs_0)
module_objs += $(d6ee6fa2_branchDperceptron_objs_0)

###
# Build ID: d6ee6fa2
# Module: branchDtage_sc_l
# Source: branch/tage_sc_l
# Destination: .csconfig/test/d6ee6fa2/branchDtage_sc_l
###

d6ee6fa2_branchDtage_sc_l_dirs_0 = .csconfig/test/d6ee6fa2/branchDtage_sc_l
d6ee6fa2_branchDtage_sc_l_objs_0 = .csconfig/test/d6ee6fa2/branchDtage_sc_l/tage_sc_l.o
$(d6ee6fa2_branchDtage_sc_l_objs_0): .csconfig/test/d6ee6fa2/branchDtage_sc_l/%.o: branch/tage_sc_l/%.cc | $(d6ee6fa2_branchDtage_sc_l_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/branchDtage_sc_l/*.d))

$(d6ee6fa2_branchDtage_sc_l_objs_0): CPPFLAGS += -Ibranch/tage_sc_l
$(d6ee6fa2_branchDtage_sc_l_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_branchDtage_sc_l_objs_0): CPPFLAGS += -include branchDtage_sc_l.inc
$(d6ee6fa2_branchDtage_sc_l_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_branchDtage_sc_l_objs_0)
module_dirs += $(d6ee6fa2_branchDtage_sc_l_dirs_0)
module_objs += $(d6ee6fa2_branchDtage_sc_l_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDDHJOLT_instr
# Source: prefetcher/D-JOLT_instr
# Destination: .csconfig/test/d6ee6fa2/prefetcherDDHJOLT_instr
###

d6ee6fa2_prefetcherDDHJOLT_instr_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDDHJOLT_instr
d6ee6fa2_prefetcherDDHJOLT_instr_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDDHJOLT_instr/d_jolt.o
$(d6ee6fa2_prefetcherDDHJOLT_instr_objs_0): .csconfig/test/d6ee6fa2/prefetcherDDHJOLT_instr/%.o: prefetcher/D-JOLT_instr/%.cc | $(d6ee6fa2_prefetcherDDHJOLT_instr_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDDHJOLT_instr/*.d))

$(d6ee6fa2_prefetcherDDHJOLT_instr_objs_0): CPPFLAGS += -Iprefetcher/D-JOLT_instr
$(d6ee6fa2_prefetcherDDHJOLT_instr_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDDHJOLT_instr_objs_0): CPPFLAGS += -include prefetcherDDHJOLT_instr.inc
$(d6ee6fa2_prefetcherDDHJOLT_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDDHJOLT_instr_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDDHJOLT_instr_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDDHJOLT_instr_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDFNLHMMA_instr
# Source: prefetcher/FNL-MMA_instr
# Destination: .csconfig/test/d6ee6fa2/prefetcherDFNLHMMA_instr
###

d6ee6fa2_prefetcherDFNLHMMA_instr_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDFNLHMMA_instr
d6ee6fa2_prefetcherDFNLHMMA_instr_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDFNLHMMA_instr/fnl_mma.o
$(d6ee6fa2_prefetcherDFNLHMMA_instr_objs_0): .csconfig/test/d6ee6fa2/prefetcherDFNLHMMA_instr/%.o: prefetcher/FNL-MMA_instr/%.cc | $(d6ee6fa2_prefetcherDFNLHMMA_instr_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDFNLHMMA_instr/*.d))

$(d6ee6fa2_prefetcherDFNLHMMA_instr_objs_0): CPPFLAGS += -Iprefetcher/FNL-MMA_instr
$(d6ee6fa2_prefetcherDFNLHMMA_instr_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDFNLHMMA_instr_objs_0): CPPFLAGS += -include prefetcherDFNLHMMA_instr.inc
$(d6ee6fa2_prefetcherDFNLHMMA_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDFNLHMMA_instr_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDFNLHMMA_instr_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDFNLHMMA_instr_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDISCA_Entangling_4Ke_instr
# Source: prefetcher/ISCA_Entangling_4Ke_instr
# Destination: .csconfig/test/d6ee6fa2/prefetcherDISCA_Entangling_4Ke_instr
###

d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDISCA_Entangling_4Ke_instr
d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDISCA_Entangling_4Ke_instr/ISCA_Entangling_4Ke.o
$(d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_objs_0): .csconfig/test/d6ee6fa2/prefetcherDISCA_Entangling_4Ke_instr/%.o: prefetcher/ISCA_Entangling_4Ke_instr/%.cc | $(d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDISCA_Entangling_4Ke_instr/*.d))

$(d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_objs_0): CPPFLAGS += -Iprefetcher/ISCA_Entangling_4Ke_instr
$(d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_objs_0): CPPFLAGS += -include prefetcherDISCA_Entangling_4Ke_instr.inc
$(d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDISCA_Entangling_4Ke_instr_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDip_stride
# Source: prefetcher/ip_stride
# Destination: .csconfig/test/d6ee6fa2/prefetcherDip_stride
###

d6ee6fa2_prefetcherDip_stride_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDip_stride
d6ee6fa2_prefetcherDip_stride_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDip_stride/ip_stride.o
$(d6ee6fa2_prefetcherDip_stride_objs_0): .csconfig/test/d6ee6fa2/prefetcherDip_stride/%.o: prefetcher/ip_stride/%.cc | $(d6ee6fa2_prefetcherDip_stride_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDip_stride/*.d))

$(d6ee6fa2_prefetcherDip_stride_objs_0): CPPFLAGS += -Iprefetcher/ip_stride
$(d6ee6fa2_prefetcherDip_stride_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDip_stride_objs_0): CPPFLAGS += -include prefetcherDip_stride.inc
$(d6ee6fa2_prefetcherDip_stride_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDip_stride_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDip_stride_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDip_stride_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDmini_djolt_instr
# Source: prefetcher/mini_djolt_instr
# Destination: .csconfig/test/d6ee6fa2/prefetcherDmini_djolt_instr
###

d6ee6fa2_prefetcherDmini_djolt_instr_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDmini_djolt_instr
d6ee6fa2_prefetcherDmini_djolt_instr_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDmini_djolt_instr/mini_djolt.o
$(d6ee6fa2_prefetcherDmini_djolt_instr_objs_0): .csconfig/test/d6ee6fa2/prefetcherDmini_djolt_instr/%.o: prefetcher/mini_djolt_instr/%.cc | $(d6ee6fa2_prefetcherDmini_djolt_instr_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDmini_djolt_instr/*.d))

$(d6ee6fa2_prefetcherDmini_djolt_instr_objs_0): CPPFLAGS += -Iprefetcher/mini_djolt_instr
$(d6ee6fa2_prefetcherDmini_djolt_instr_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDmini_djolt_instr_objs_0): CPPFLAGS += -include prefetcherDmini_djolt_instr.inc
$(d6ee6fa2_prefetcherDmini_djolt_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDmini_djolt_instr_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDmini_djolt_instr_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDmini_djolt_instr_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDnext_line
# Source: prefetcher/next_line
# Destination: .csconfig/test/d6ee6fa2/prefetcherDnext_line
###

d6ee6fa2_prefetcherDnext_line_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDnext_line
d6ee6fa2_prefetcherDnext_line_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDnext_line/next_line.o
$(d6ee6fa2_prefetcherDnext_line_objs_0): .csconfig/test/d6ee6fa2/prefetcherDnext_line/%.o: prefetcher/next_line/%.cc | $(d6ee6fa2_prefetcherDnext_line_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDnext_line/*.d))

$(d6ee6fa2_prefetcherDnext_line_objs_0): CPPFLAGS += -Iprefetcher/next_line
$(d6ee6fa2_prefetcherDnext_line_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDnext_line_objs_0): CPPFLAGS += -include prefetcherDnext_line.inc
$(d6ee6fa2_prefetcherDnext_line_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDnext_line_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDnext_line_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDnext_line_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDnext_line_instr
# Source: prefetcher/next_line_instr
# Destination: .csconfig/test/d6ee6fa2/prefetcherDnext_line_instr
###

d6ee6fa2_prefetcherDnext_line_instr_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDnext_line_instr
d6ee6fa2_prefetcherDnext_line_instr_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDnext_line_instr/next_line.o
$(d6ee6fa2_prefetcherDnext_line_instr_objs_0): .csconfig/test/d6ee6fa2/prefetcherDnext_line_instr/%.o: prefetcher/next_line_instr/%.cc | $(d6ee6fa2_prefetcherDnext_line_instr_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDnext_line_instr/*.d))

$(d6ee6fa2_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -Iprefetcher/next_line_instr
$(d6ee6fa2_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -include prefetcherDnext_line_instr.inc
$(d6ee6fa2_prefetcherDnext_line_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDnext_line_instr_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDnext_line_instr_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDnext_line_instr_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDno
# Source: prefetcher/no
# Destination: .csconfig/test/d6ee6fa2/prefetcherDno
###

d6ee6fa2_prefetcherDno_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDno
d6ee6fa2_prefetcherDno_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDno/no.o
$(d6ee6fa2_prefetcherDno_objs_0): .csconfig/test/d6ee6fa2/prefetcherDno/%.o: prefetcher/no/%.cc | $(d6ee6fa2_prefetcherDno_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDno/*.d))

$(d6ee6fa2_prefetcherDno_objs_0): CPPFLAGS += -Iprefetcher/no
$(d6ee6fa2_prefetcherDno_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDno_objs_0): CPPFLAGS += -include prefetcherDno.inc
$(d6ee6fa2_prefetcherDno_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDno_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDno_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDno_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDno_instr
# Source: prefetcher/no_instr
# Destination: .csconfig/test/d6ee6fa2/prefetcherDno_instr
###

d6ee6fa2_prefetcherDno_instr_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDno_instr
d6ee6fa2_prefetcherDno_instr_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDno_instr/no.o
$(d6ee6fa2_prefetcherDno_instr_objs_0): .csconfig/test/d6ee6fa2/prefetcherDno_instr/%.o: prefetcher/no_instr/%.cc | $(d6ee6fa2_prefetcherDno_instr_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDno_instr/*.d))

$(d6ee6fa2_prefetcherDno_instr_objs_0): CPPFLAGS += -Iprefetcher/no_instr
$(d6ee6fa2_prefetcherDno_instr_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDno_instr_objs_0): CPPFLAGS += -include prefetcherDno_instr.inc
$(d6ee6fa2_prefetcherDno_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDno_instr_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDno_instr_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDno_instr_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDspp_dev
# Source: prefetcher/spp_dev
# Destination: .csconfig/test/d6ee6fa2/prefetcherDspp_dev
###

d6ee6fa2_prefetcherDspp_dev_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDspp_dev
d6ee6fa2_prefetcherDspp_dev_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDspp_dev/spp_dev.o
$(d6ee6fa2_prefetcherDspp_dev_objs_0): .csconfig/test/d6ee6fa2/prefetcherDspp_dev/%.o: prefetcher/spp_dev/%.cc | $(d6ee6fa2_prefetcherDspp_dev_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDspp_dev/*.d))

$(d6ee6fa2_prefetcherDspp_dev_objs_0): CPPFLAGS += -Iprefetcher/spp_dev
$(d6ee6fa2_prefetcherDspp_dev_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDspp_dev_objs_0): CPPFLAGS += -include prefetcherDspp_dev.inc
$(d6ee6fa2_prefetcherDspp_dev_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDspp_dev_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDspp_dev_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDspp_dev_objs_0)

###
# Build ID: d6ee6fa2
# Module: prefetcherDva_ampm_lite
# Source: prefetcher/va_ampm_lite
# Destination: .csconfig/test/d6ee6fa2/prefetcherDva_ampm_lite
###

d6ee6fa2_prefetcherDva_ampm_lite_dirs_0 = .csconfig/test/d6ee6fa2/prefetcherDva_ampm_lite
d6ee6fa2_prefetcherDva_ampm_lite_objs_0 = .csconfig/test/d6ee6fa2/prefetcherDva_ampm_lite/va_ampm_lite.o
$(d6ee6fa2_prefetcherDva_ampm_lite_objs_0): .csconfig/test/d6ee6fa2/prefetcherDva_ampm_lite/%.o: prefetcher/va_ampm_lite/%.cc | $(d6ee6fa2_prefetcherDva_ampm_lite_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/prefetcherDva_ampm_lite/*.d))

$(d6ee6fa2_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -Iprefetcher/va_ampm_lite
$(d6ee6fa2_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -include prefetcherDva_ampm_lite.inc
$(d6ee6fa2_prefetcherDva_ampm_lite_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_prefetcherDva_ampm_lite_objs_0)
module_dirs += $(d6ee6fa2_prefetcherDva_ampm_lite_dirs_0)
module_objs += $(d6ee6fa2_prefetcherDva_ampm_lite_objs_0)

###
# Build ID: d6ee6fa2
# Module: replacementDdrrip
# Source: replacement/drrip
# Destination: .csconfig/test/d6ee6fa2/replacementDdrrip
###

d6ee6fa2_replacementDdrrip_dirs_0 = .csconfig/test/d6ee6fa2/replacementDdrrip
d6ee6fa2_replacementDdrrip_objs_0 = .csconfig/test/d6ee6fa2/replacementDdrrip/drrip.o
$(d6ee6fa2_replacementDdrrip_objs_0): .csconfig/test/d6ee6fa2/replacementDdrrip/%.o: replacement/drrip/%.cc | $(d6ee6fa2_replacementDdrrip_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/replacementDdrrip/*.d))

$(d6ee6fa2_replacementDdrrip_objs_0): CPPFLAGS += -Ireplacement/drrip
$(d6ee6fa2_replacementDdrrip_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_replacementDdrrip_objs_0): CPPFLAGS += -include replacementDdrrip.inc
$(d6ee6fa2_replacementDdrrip_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_replacementDdrrip_objs_0)
module_dirs += $(d6ee6fa2_replacementDdrrip_dirs_0)
module_objs += $(d6ee6fa2_replacementDdrrip_objs_0)

###
# Build ID: d6ee6fa2
# Module: replacementDhotloop
# Source: replacement/hotloop
# Destination: .csconfig/test/d6ee6fa2/replacementDhotloop
###

d6ee6fa2_replacementDhotloop_dirs_0 = .csconfig/test/d6ee6fa2/replacementDhotloop
d6ee6fa2_replacementDhotloop_objs_0 = .csconfig/test/d6ee6fa2/replacementDhotloop/hotloop.o
$(d6ee6fa2_replacementDhotloop_objs_0): .csconfig/test/d6ee6fa2/replacementDhotloop/%.o: replacement/hotloop/%.cc | $(d6ee6fa2_replacementDhotloop_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/replacementDhotloop/*.d))

$(d6ee6fa2_replacementDhotloop_objs_0): CPPFLAGS += -Ireplacement/hotloop
$(d6ee6fa2_replacementDhotloop_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_replacementDhotloop_objs_0): CPPFLAGS += -include replacementDhotloop.inc
$(d6ee6fa2_replacementDhotloop_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_replacementDhotloop_objs_0)
module_dirs += $(d6ee6fa2_replacementDhotloop_dirs_0)
module_objs += $(d6ee6fa2_replacementDhotloop_objs_0)

###
# Build ID: d6ee6fa2
# Module: replacementDhotloop_lru
# Source: replacement/hotloop_lru
# Destination: .csconfig/test/d6ee6fa2/replacementDhotloop_lru
###

d6ee6fa2_replacementDhotloop_lru_dirs_0 = .csconfig/test/d6ee6fa2/replacementDhotloop_lru
d6ee6fa2_replacementDhotloop_lru_objs_0 = .csconfig/test/d6ee6fa2/replacementDhotloop_lru/hotloop_lru.o
$(d6ee6fa2_replacementDhotloop_lru_objs_0): .csconfig/test/d6ee6fa2/replacementDhotloop_lru/%.o: replacement/hotloop_lru/%.cc | $(d6ee6fa2_replacementDhotloop_lru_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/replacementDhotloop_lru/*.d))

$(d6ee6fa2_replacementDhotloop_lru_objs_0): CPPFLAGS += -Ireplacement/hotloop_lru
$(d6ee6fa2_replacementDhotloop_lru_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_replacementDhotloop_lru_objs_0): CPPFLAGS += -include replacementDhotloop_lru.inc
$(d6ee6fa2_replacementDhotloop_lru_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_replacementDhotloop_lru_objs_0)
module_dirs += $(d6ee6fa2_replacementDhotloop_lru_dirs_0)
module_objs += $(d6ee6fa2_replacementDhotloop_lru_objs_0)

###
# Build ID: d6ee6fa2
# Module: replacementDlru
# Source: replacement/lru
# Destination: .csconfig/test/d6ee6fa2/replacementDlru
###

d6ee6fa2_replacementDlru_dirs_0 = .csconfig/test/d6ee6fa2/replacementDlru
d6ee6fa2_replacementDlru_objs_0 = .csconfig/test/d6ee6fa2/replacementDlru/lru.o
$(d6ee6fa2_replacementDlru_objs_0): .csconfig/test/d6ee6fa2/replacementDlru/%.o: replacement/lru/%.cc | $(d6ee6fa2_replacementDlru_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/replacementDlru/*.d))

$(d6ee6fa2_replacementDlru_objs_0): CPPFLAGS += -Ireplacement/lru
$(d6ee6fa2_replacementDlru_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_replacementDlru_objs_0): CPPFLAGS += -include replacementDlru.inc
$(d6ee6fa2_replacementDlru_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_replacementDlru_objs_0)
module_dirs += $(d6ee6fa2_replacementDlru_dirs_0)
module_objs += $(d6ee6fa2_replacementDlru_objs_0)

###
# Build ID: d6ee6fa2
# Module: replacementDship
# Source: replacement/ship
# Destination: .csconfig/test/d6ee6fa2/replacementDship
###

d6ee6fa2_replacementDship_dirs_0 = .csconfig/test/d6ee6fa2/replacementDship
d6ee6fa2_replacementDship_objs_0 = .csconfig/test/d6ee6fa2/replacementDship/ship.o
$(d6ee6fa2_replacementDship_objs_0): .csconfig/test/d6ee6fa2/replacementDship/%.o: replacement/ship/%.cc | $(d6ee6fa2_replacementDship_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/replacementDship/*.d))

$(d6ee6fa2_replacementDship_objs_0): CPPFLAGS += -Ireplacement/ship
$(d6ee6fa2_replacementDship_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_replacementDship_objs_0): CPPFLAGS += -include replacementDship.inc
$(d6ee6fa2_replacementDship_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_replacementDship_objs_0)
module_dirs += $(d6ee6fa2_replacementDship_dirs_0)
module_objs += $(d6ee6fa2_replacementDship_objs_0)

###
# Build ID: d6ee6fa2
# Module: replacementDsrrip
# Source: replacement/srrip
# Destination: .csconfig/test/d6ee6fa2/replacementDsrrip
###

d6ee6fa2_replacementDsrrip_dirs_0 = .csconfig/test/d6ee6fa2/replacementDsrrip
d6ee6fa2_replacementDsrrip_objs_0 = .csconfig/test/d6ee6fa2/replacementDsrrip/srrip.o
$(d6ee6fa2_replacementDsrrip_objs_0): .csconfig/test/d6ee6fa2/replacementDsrrip/%.o: replacement/srrip/%.cc | $(d6ee6fa2_replacementDsrrip_dirs_0)
-include $(wildcard .csconfig/test/d6ee6fa2/replacementDsrrip/*.d))

$(d6ee6fa2_replacementDsrrip_objs_0): CPPFLAGS += -Ireplacement/srrip
$(d6ee6fa2_replacementDsrrip_objs_0): CPPFLAGS += -I.csconfig/test/d6ee6fa2/inc
$(d6ee6fa2_replacementDsrrip_objs_0): CPPFLAGS += -include replacementDsrrip.inc
$(d6ee6fa2_replacementDsrrip_objs_0): CXXFLAGS += -Wno-unused-parameter
test/bin/000-test-main: $(d6ee6fa2_replacementDsrrip_objs_0)
module_dirs += $(d6ee6fa2_replacementDsrrip_dirs_0)
module_objs += $(d6ee6fa2_replacementDsrrip_objs_0)